### ISSUE TITLE
app.toml vat-transcript-archive-dir= throws unless it is on the same volume as TMPDIR

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#10239]
## Describe the bug

When updating my follower node for upgrade17, I configured it to save old transcript spans to a subdirectory of the main agoric state directory:

```toml
[swingset]
# Archival of historical (i.e., closed) vat transcript spans to gzipped files.
vat-transcript-archive-dir = "/home/warner/.agoric/data/agoric/old-transcripts"
```

My follower is configured to use `~warner/.agoric/` for its state, with the config in `~warner/.agoric/config/` and the data in `~warner/.agoric/data/`. And `~warner/.agoric` is actually a symlink to `/data2/dot-agoric/`, where `/data2` is a larger volume (using ZFS, with which I can make periodic fs-level snapshots).

At restart time, I got a crash from golang:

```
2024-10-07T20:28:16.037Z SwingSet: kernel: attempting to upgrade vat v135 from incarnation 0 to source b1-9c297baeb07fc2341e3ddc27
e95737af3f0bef80bb85d43da70d3bc3eb2aa2a497bc3afd4a78c6c1e3ea1c8ddc5399d2980638d239b6eea040b239eb8767573d
2024-10-07T20:28:16.257Z SwingSet: kernel: ##### KERNEL PANIC: error during tryProcessMessage: Error: EXDEV: cross-device link not permitted, rename '/tmp/transcript.v135.5.16-18380-ag9NZbnIP0bB-.gz' -> '/home/warner/.agoric/data/agoric/old-transcripts/transcript.v135.5.16.gz' #####
2024-10-07T20:28:16.257Z block-manager: END_BLOCK error: (Error#1)
Error#1: EXDEV: cross-device link not permitted, rename '/tmp/transcript.v135.5.16-18380-ag9NZbnIP0bB-.gz' -> '/home/warner/.agoric/data/agoric/old-transcripts/transcript.v135.5.16.gz'

  at Object.renameSync (node:fs:1035:3)
  at packages/swing-store/src/archiver.js:75:10
  at async closeSpan (packages/swing-store/src/transcriptStore.js:382:7)
  at async doSpanRollover (packages/swing-store/src/transcriptStore.js:401:5)
  at async processUpgradeVat (.../swingset-vat/src/kernel/kernel.js:1014:22)
  at async deliverRunQueueEvent (.../swingset-vat/src/kernel/kernel.js:1303:15)
  at async processDeliveryMessage (.../swingset-vat/src/kernel/kernel.js:1342:20)
  at async tryProcessMessage (.../swingset-vat/src/kernel/kernel.js:1443:14)
  at async Object.run (.../swingset-vat/src/kernel/kernel.js:1969:19)
  at async crankScheduler (packages/cosmic-swingset/src/kernel-stats.js:464:5)
  at async runSwingset (packages/cosmic-swingset/src/launch-chain.js:467:7)
  at async processActions (packages/cosmic-swingset/src/launch-chain.js:674:19)
  at async runKernel (packages/cosmic-swingset/src/launch-chain.js:692:7)
  at async endBlock (packages/cosmic-swingset/src/launch-chain.js:736:5)

portHandler threw (Error#1)
```

It looks like the new span-saving code writes the temporary file to `$TMPDIR`, and then attempts to hardlink it into place in the `vat-transcript-archive-dir` directory, and this only works if both are on the same device (volume).

As a workaround, I set my $TMPDIR to `/data2/tmpdir`, but really we should not impose this sort of constraint on users.

The likely fix is to have swingstore create the temporary file next to the final file, with an extra extension like `.tmp`. This is the standard pattern for atomic writes (create a temp filename out of the real target filename by adding an extension, write to the tempfile, close the tempfile, then `mv()` into place). I'm not sure where the hardlink is coming from, whether it's our code or something in a tempfile library, but if we can't avoid doing the hardlink, then we need to configure it to not use $TMPDIR.

## Platform Environment

* Node.js v18.20.4
* Linux 5.15.0 (ubuntu 22.04.5 LTS), with ZFS
* agoric-sdk as of `agoric-upgrade-17`

**Comment by mhofman** [comment]
> I'm not sure where the hardlink is coming from

`renameSync` uses a `rename` syscall which works with hardlinks I believe. [EXDEV](https://man7.org/linux/man-pages/man2/rename.2.html#:~:text=exdev) is documented as an error for that syscall.
