### ISSUE TITLE
slog-to-otel does not handle slow vat termination

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#10405]
## Describe the bug
Errors from https://github.com/Agoric/agoric-sdk/actions/runs/11692254542/job/32561236661?pr=10165 :

<details><summary>Unknown crank-start message.type cleanup-terminated-vat</summary>

```
Error tracing slog: {
  type: 'crank-start',
  crankType: 'delivery',
  crankNum: 4913n,
  message: {
    type: 'cleanup-terminated-vat',
    vatID: 'v16',
    budget: { default: 5, kv: 50 }
  },
  time: 1730840617.433475,
  monotime: 167.98721473999984
} (Error#1)
Error#1: Unknown crank-start message.type cleanup-terminated-vat

  at extractMessageAttrs (packages/telemetry/src/slog-to-otel.js:269:13)
  at slogSender (packages/telemetry/src/slog-to-otel.js:1035:46)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:1082:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:154:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:116:15)
  at process.emit (node:events:517:28)
```

</details>
<details><summary>Unknown slog type: vat-cleanup</summary>

```
Error tracing slog: {
  type: 'vat-cleanup',
  vatID: 'v16',
  work: { kv: 8, snapshots: 1, transcripts: 2 },
  time: 1730840617.435071,
  monotime: 167.98881064499997
} (Error#2)
Error#2: Unknown slog type: vat-cleanup

  at slogSender (packages/telemetry/src/slog-to-otel.js:1075:13)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:1082:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:154:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:116:15)
  at process.emit (node:events:517:28)
```

</details>
<details><summary>Unknown slog type: vat-cleanup-complete</summary>

```
Error tracing slog: {
  type: 'vat-cleanup-complete',
  vatID: 'v16',
  time: 1730840617.43517,
  monotime: 167.98891011099994
} (Error#3)
Error#3: Unknown slog type: vat-cleanup-complete

  at slogSender (packages/telemetry/src/slog-to-otel.js:1075:13)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:1082:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:154:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:116:15)
  at process.emit (node:events:517:28)
```

</details>

**Comment by gibson042** [comment]
Errors from ollinet upgrade to upgrade-18-rc2 :

* Unknown slog type: cosmic-swingset-inject-kernel-upgrade-events
* Unknown crank-start message.type upgrade-vat

**Comment by gibson042** [comment]
Issues from mainfork testing:
* A slog entry with `jsonPayload` including `"message": { "type": "cleanup-terminated-vat", "vatID": "v156", "budget": { "default": null } }` was _followed_ by one with `jsonPayload` including `"vatID": "v156", "type": "create-vat"`, which obviously didn't happen (as confirmed by direct slogfile inspection).

**Comment by mhofman** [comment]
I'm tempted to say we should not bother fixing this until we work on https://github.com/Agoric/agoric-sdk/issues/10799, especially if we disabled otel-trace in integration tests (https://github.com/Agoric/agoric-sdk/issues/10798)
