### ISSUE TITLE
bundled code has useless source path

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#3843]
## Describe the bug

When running code in vats and zoe contracts after bundling, the source link goes through `/bundled-source/.../packages` rather than using a `file://` link that the debugger would understand.

## To Reproduce
run the tests in `packages/treasury/test/test-stablecoin.js`

## Expected behavior

Stack traces currently look like this.  Notice that the first three lines include `file://Users/chrishibbert/...` locators, while the fourth line has `/bundled-source/.../packages/governance`. The debugger (WebStorm, but I presume others are similar) can link the first three up, but not the one with the code I'm interested in.

```
  at makeError (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:2875:17)
  at fail (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3003:20)
  at baseAssert (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3021:13)
  at Object.start (/bundled-source/.../packages/governance/src/contractGovernor.js:114:3)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Platform Environment
 - what OS are you using? what version of Node.js?
     MacOS,  Node v14.17.0
 - is there anything special/unusual about your platform?
  Don't think so.
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
    @agoric/access-token@0.4.13-19-g5e3f2ff88

**Comment by kriskowal** [comment]
Thank you. There is a tension between deterministic archive/bundle generation/transmissibility and locally accurate source URL’s for debuggers. With Zip files, we might be able to defer appending a source URL comment to the source under test until after extraction, but we won’t have an opportunity to do the same for `nestedEvaluate` Rollup bundles.

**Comment by Chris-Hibbert** [comment]
Currently, stack traces aren't showing any source info at all: 

```javascript
RemoteError(error:liveSlots:v9#70001)#1 ERROR_NOTE: Rejection from: (Error#2) : 16 . 0
RemoteError(error:liveSlots:v9#70001)#1 ERROR_NOTE: Rejection from: (Error#3) : 1 . 1
RemoteError(error:liveSlots:v9#70001)#1 ERROR_NOTE: Sent as error:liveSlots:v3#70001
Error#2: Event: 13.3
Error: Event: 13.3
 at construct ()
 at Error (/Users/chrishibbert/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:8833)
 at trackTurns (/Users/chrishibbert/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:10534)
 at handle (/Users/chrishibbert/agoric-sdk/packages/SwingSet/src/kernel/vatManager/lockdown-subprocess-xsnap.js:11241)
 at (#399:39)
 at voteToChangeParameter (#183:34)
 at voteToChangeParameter ()
 at bootstrap (#183:250)
 at ()
 at ()
```

**Comment by Chris-Hibbert** [comment]
This problem is no longer present, and the code that provoked it has been moved somewhere different enough that I don't recognize the test any more.  

Closing.
