### ISSUE TITLE
yarn install failing Node 16.9.1

### ISSUE THREAD

**Issue by danishyasin33** [Agoric/Agoric#3855]
## Describe the bug
`yarn install` errors while installing `agoric-sdk` using Node v16.9.1. Log attached below. 

## To Reproduce
1. Install node 16.9.1 using nvm
2. on `agoric-sdk` master, run `yarn install`

## Expected behavior
Should install successfully

## Platform Environment
 - Microsoft Windows 10 Version 10.0.19043 Build 19043
 - Using `Linux 5.10.16.3-microsoft-standard-WSL2` on top of it.

## Additional context
```
[5/5] Building fresh packages...
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
[3/6] ⠠ node-lmdb
[-/6] ⠠ waiting...
error /mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@16.9.1 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.9.1 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-linux-glibc-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@16.9.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@16.9.1 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/danishyasin33/.cache/node-gyp/16.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/danishyasin33/.cache/node-gyp/16.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/danishyasin33/.cache/node-gyp/16.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/lib/configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
gyp ERR! command "/home/danishyasin33/.nvm/versions/node/v16.9.1/bin/node" "/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas
gyp ERR! node -v v16.9.1
gyp ERR! node-gyp -v v8.2.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/danishyasin33/.nvm/versions/node/v16.9.1/bin/node /mnt/g/Development/Agoric/agoric-sdk/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/g/Development/Agoric/agoric-sdk/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
node-pre-gyp ERR! command "/home/danishyasin33/.nvm/versions/node/v16.9.1/bin/node" "/mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/g/Development/Agoric/agoric-sdk/node_modules/canvas
node-pre-gyp ERR! node -v v16.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/home/danishyasin33/.nvm/versions/node/v16.9.1/bin/node /mnt/g/Development/Agoric/agoric-sdk/node_mod
```

**Comment by dckc** [comment]
I just saw another problem report with node 16:

node v16.11.1 and yarn version 1.22.5
On archlinux
Kernel 5.10.72-1-lts

```
agoric install
...
error /home/.../Desktop/blockchain/demo/node_modules/node-lmdb: Command failed.
...
error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
```

**Comment by dckc** [comment]
@michaelfig first it was re2 (#3785) and now we have canvas and lmdb failing to build. Clues?

**Comment by michaelfig** [comment]
> @michaelfig first it was re2 (#3785) and now we have canvas and lmdb failing to build. Clues?

Why would `canvas` fail?  It's not even used by `agoric-sdk` anymore.  Could they be using an older SDK (before we had Node 16 support)?

**Comment by dckc** [comment]
@robert-zaremba reports another node 16 build issue:
following the tutorial: https://agoric.com/documentation/getting-started/start-a-project.html
After executing `agoric init demo; cd demo; agoric install`:

```
make: Entering directory '/home/robert/projects/agoric/demo/node_modules/node-lmdb/build'
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
In file included from /home/robert/.cache/node-gyp/16.11.1/include/node/v8.h:30,
                 from ../src/node-lmdb.h:29,
                 from ../src/node-lmdb.cpp:24:
/home/robert/.cache/node-gyp/16.11.1/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/home/robert/.cache/node-gyp/16.11.1/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
```

Linux (Manjaro), Node.js v16.11.1
agoricdev-5.2 as well as master from Sunday
a9458c75b6d09572b54a346a6e538f9c26e0e3e9

same symptoms with node 16.13

work-around / solution: `CXXFLAGS="--std=c++14" agoric install` as noted in https://github.com/Venemo/node-lmdb/issues/190#issuecomment-975970238

**Comment by turadg** [comment]
Obsoleted. Node 16 is EOL.
