### ISSUE TITLE
SwingSet: unable to run demos 'Error#1: config devices.0: ...'

### ISSUE THREAD

**Issue by danwt** [Agoric/Agoric#4066]
_Surfaced from @informalsystems audit of Agoric/agoric-sdk/SwingSet at hash f6a87bab45bb6ac611f91e20a3c93baf1b180294_

## Describe the bug

Trying to run the demos in SwingSet/demo per the instructions in the README gives an error

```bash
bin/vat run demo/encouragementBot

> 
> Removing intrinsics.Object.hasOwn
> (Error#1)
> Error#1: config devices.0: you must specify one of: "bundleName", "bundle", "bundleSpec", or "sourceSpec"
> 
>   at validateBundleDescriptor (packages/SwingSet/src/initializeSwingset.js:392:13)
>   at bundleBundles (packages/SwingSet/src/initializeSwingset.js:404:9)
>   at initializeSwingset (packages/SwingSet/src/initializeSwingset.js:429:9)
>   at async buildVatController (packages/SwingSet/src/controller.js:416:23)
>   at async main (packages/SwingSet/tools/vat.js:36:22)

```

## To Reproduce
```bash
# clone agoric-sdk
cd agoric-sdk;
yarn install;
yarn build;
cd packages/SwingSet;
bin/vat run demo/encouragementBot
```

## Expected behavior
The demo to run

## Platform Environment
 - what OS are you using? what version of Node.js? node v16.13.0, Ubuntu 21.04
 - is there anything special/unusual about your platform? No
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) @agoric/sdk@10.0.2-144-gf6a87bab4

**Comment by ivanlei** [comment]
Adding latest error
```shell
➜  SwingSet git:(master) ✗ bin/vat run demo/encouragementBot
SES_UNHANDLED_REJECTION: (Error#1)
Error#1: config.devices.0: need =1 of bundle/bundleSpec/sourceSpec/bundleName, got

  at packages/SwingSet/src/controller/initializeSwingset.js:472:15
  at async Promise.all (index 0)
  at async processGroup (packages/SwingSet/src/controller/initializeSwingset.js:475:27)
  at async initializeSwingset (packages/SwingSet/src/controller/initializeSwingset.js:504:34)
  at async buildVatController (packages/SwingSet/src/controller/controller.js:553:23)
  at async main (packages/SwingSet/tools/vat.js:36:22)
```
