### ISSUE TITLE
Update dapp-simple-exchange

### ISSUE THREAD

**Issue by ccfiel** [Agoric/Agoric#4109]
Previous Title: underlying failures: Unexpected export statement in CJS module.

## Describe the bug
I tried to to deploy the contract with this template https://github.com/Agoric/dapp-simple-exchange but got this error
```
chris@chris-zenBook:~/agoric/exchange$ agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/chris/agoric/exchange/contract/deploy.js
agoric: deploy: Deploy script will run with standardthings/esm emulation
agoric: (TypeError#1)
TypeError#1: Failed to load module "./src/contract.js" in package "file:///home/chris/agoric/exchange/contract/" (1 underlying failures: Unexpected export statement in CJS module.
  at file:///home/chris/agoric/exchange/contract/src/contract.js:6:8

  at async bundleZipBase64 (packages/bundle-source/src/index.js:136:17)
  at async deployContract (/home/chris/agoric/exchange/contract/deploy.js:51:18)
  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:264:13)
```

## To Reproduce
1. agoric init exchange --dapp-template dapp-simple-exchange
2. cd exchange
3. agoric install
4. agoric start --reset
5. Open another shell, go to your exchange directory
6. In the deploy shell, agoric deploy ./contract/deploy.js ./api/deploy.js
7. error will display
 
```chris@chris-zenBook:~/agoric/exchange$ agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /home/chris/agoric/exchange/contract/deploy.js
agoric: deploy: Deploy script will run with standardthings/esm emulation
agoric: (TypeError#1)
TypeError#1: Failed to load module "./src/contract.js" in package "file:///home/chris/agoric/exchange/contract/" (1 underlying failures: Unexpected export statement in CJS module.
  at file:///home/chris/agoric/exchange/contract/src/contract.js:6:8

  at async bundleZipBase64 (packages/bundle-source/src/index.js:136:17)
  at async deployContract (/home/chris/agoric/exchange/contract/deploy.js:51:18)
  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:264:13)
```

## Expected behavior
It should deploy the contract

## Platform Environment
 - Ubuntu 20.04
 - Node v14.18.0
 - agoric 0.13.19

**Comment by dckc** [comment]
@kriskowal any chance it's obvious to you what's going on here?

**Comment by kriskowal** [comment]
Aye. This is what occurs when `"type": "module"` is missing from `package.json`.

**Comment by kriskowal** [comment]
Except that this says it’s running the deploy script with ESM emulation (`-r esm`) which actually *requires* that `"type": "module"` be absent in `package.json`. 🤔

**Comment by kriskowal** [comment]
Oh, that’s fine. The deploy script is running under `-r esm` but the contract is not. So, `contract/package.json` *must* have `"type": "module"`. It probably would not hurt to add `"type": "module"` to the top-level `package.json`, but the example dapp might not be set up for that yet. Things like `__dirname` need to be migrated to `import.meta.url`.

**Comment by kriskowal** [comment]
@ccfiel Can you verify that adding  `"type": "module"` `contract/package.json` addresses you the issue you’re observing. I can in parallel attempt to reproduce the error.

**Comment by kriskowal** [comment]
@michaelfig tells me that `dapp-simple-exchange` is generally in disrepair, so this might be just the first in a sequence of problems. The ball is in my court unless someone gets to this first.

**Comment by kriskowal** [comment]
Sending to @michaelfig for MN-1 triage. I don’t know whether the plan is to scuttle or update. @samsiegart might be in the vicinity of dapp test automation.

**Comment by michaelfig** [comment]
Not MN-1.
