### ISSUE TITLE
vref not on clist

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4179]
## The bug

See #4178 for a snapshot of the code.

```
error during syscall translation: (Error#1)
Error#1: vref o+47 not in clist
```

The complete test output:

```
bundling: 7.169s kernel, 4.271s contracts, 5.15s vats, 16.59s total
error during syscall translation: (Error#1)
Error#1: vref o+47 not in clist

  at mapVatSlotToKernelSlot (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:239:7)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:306:20)
  at Array.map (<anonymous>)
  at translateRetireExports (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:301:25)
  at Object.vatSyscallToKernelSyscall (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:398:16)
  at vatSyscallHandler (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:894:27)
  at syscallFromWorker (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:251:18)
  at doSyscall (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:72:11)
  at Object.retireExports (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:109:31)
  at scanForDeadObjects (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:287:15)
  at runMicrotasks (<anonymous>)
  at async bringOutYourDead (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1190:20)
  at async Object.deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:157:20)
  at async Object.deliverToVat (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:278:28)
  at async deliverAndLogToVat (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:436:30)
  at async processBringOutYourDead (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:682:19)
  at async processQueueMessage (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:801:23)
  at async Object.run (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1181:27)
  at async main (packages/governance/test/swingsetTests/contractGovernor/test-governor.js:81:3)
  at async packages/governance/test/swingsetTests/contractGovernor/test-governor.js:107:16

error Error: syscall.retireExports failed, prepare to die: syscall translation error: prepare to die during vat dispatch() of bringOutYourDead
delivery problem, terminating vat v2 syscall.retireExports failed, prepare to die: syscall translation error: prepare to die
Logging sent error stack (RemoteError#2)
RemoteError#2: vat terminated

  at fullRevive (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:368:36)
  at Object.unserialize (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:451:19)
  at notifyOnePromise (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:916:19)
  at notify (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:929:7)
  at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1161:11)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
  at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
  at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)

RemoteError#2 ERROR_NOTE: Rejection from: (Error#3) : 270 . 0
RemoteError#2 ERROR_NOTE: Rejection from: (Error#4) : 268 . 2
RemoteError#2 ERROR_NOTE: Sent as error:liveSlots:v8#70001
Nested 2 errors under RemoteError#2
  Error#3: Event: 268.2
  
    at Proxy.eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:39:49)
    at startCounter (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:30:3)
    at Alleged: questionPoser.addQuestion (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:81:12)
    at runMicrotasks (<anonymous>)
  
  Error#3 ERROR_NOTE: Caused by: (Error#4)
  Nested error under Error#3
    Error#4: Event: 267.1
    
      at deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:839:28)
      at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1156:11)
      at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
      at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
      at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)
      at runMicrotasks (<anonymous>)
    
Logging sent error stack (RemoteError(error:liveSlots:v8#70001)#5)
RemoteError(error:liveSlots:v8#70001)#5: vat terminated

  at fullRevive (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:368:36)
  at Object.unserialize (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:451:19)
  at notifyOnePromise (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:916:19)
  at notify (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:929:7)
  at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1161:11)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
  at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
  at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)

RemoteError(error:liveSlots:v8#70001)#5 ERROR_NOTE: Rejection from: (Error#6) : 253 . 0
RemoteError(error:liveSlots:v8#70001)#5 ERROR_NOTE: Rejection from: (Error#7) : 251 . 2
RemoteError(error:liveSlots:v8#70001)#5 ERROR_NOTE: Sent as error:liveSlots:v9#70001
Nested 2 errors under RemoteError(error:liveSlots:v8#70001)#5
  Error#6: Event: 251.2
  
    at Proxy.eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:39:49)
    at Alleged: governor creatorFacet.voteOnParamChange (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:117:5)
    at runMicrotasks (<anonymous>)
  
  Error#6 ERROR_NOTE: Caused by: (Error#7)
  Nested error under Error#6
    Error#7: Event: 250.1
    
      at deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:839:28)
      at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1156:11)
      at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
      at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
      at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)
      at runMicrotasks (<anonymous>)
    
Logging sent error stack (RemoteError(error:liveSlots:v9#70001)#8)
RemoteError(error:liveSlots:v9#70001)#8: vat terminated

  at fullRevive (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:368:36)
  at Object.unserialize (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:451:19)
  at notifyOnePromise (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:916:19)
  at notify (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:929:7)
  at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1161:11)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
  at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
  at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)

RemoteError(error:liveSlots:v9#70001)#8 ERROR_NOTE: Rejection from: (Error#9) : 243 . 0
RemoteError(error:liveSlots:v9#70001)#8 ERROR_NOTE: Rejection from: (Error#10) : 1 . 1
RemoteError(error:liveSlots:v9#70001)#8 ERROR_NOTE: Sent as error:liveSlots:v3#70001
Nested 2 errors under RemoteError(error:liveSlots:v9#70001)#8
  Error#9: Event: 240.3
  
    at Proxy.eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:39:49)
    at voteToChangeParameter (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:27:3)
    at Alleged: root.eval [as bootstrap] (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:228:26)
    at runMicrotasks (<anonymous>)
  
  Error#10: Event: 0.1
  
    at deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:839:28)
    at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1156:11)
    at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
    at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
    at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)
  
##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v3#70001\",\"message\":\"vat terminated\",\"name\":\"Error\"}","slots":[]} #####
Logging sent error stack (TypeError#11)
TypeError#11: Cannot deliver getPoserInvitation to target; typeof target is undefined

TypeError#11 ERROR_NOTE: Thrown from: (Error#12) : 378 . 0
TypeError#11 ERROR_NOTE: Sent as error:liveSlots:v3#70001
Nested error under TypeError#11
  Error#12: Event: 377.1
  
    at Proxy.eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:39:49)
    at Alleged: root.eval [as bootstrap] (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:262:9)
  
Logging sent error stack (RemoteTypeError(error:liveSlots:v3#70001)#13)
RemoteTypeError(error:liveSlots:v3#70001)#13: Cannot deliver "getPoserInvitation" to target; typeof target is "undefined"

  at fullRevive (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:368:36)
  at Object.unserialize (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:451:19)
  at notifyOnePromise (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:916:19)
  at notify (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:929:7)
  at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1161:11)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
  at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
  at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)

RemoteTypeError(error:liveSlots:v3#70001)#13 ERROR_NOTE: Rejection from: (Error#14) : 380 . 0
RemoteTypeError(error:liveSlots:v3#70001)#13 ERROR_NOTE: Sent as error:liveSlots:v2#70001
Nested error under RemoteTypeError(error:liveSlots:v3#70001)#13
  Error#14: Event: 379.1
  
    at deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:839:28)
    at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1156:11)
    at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
    at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
    at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)
  
Logging sent error stack (RemoteTypeError(error:liveSlots:v2#70001)#15)
RemoteTypeError(error:liveSlots:v2#70001)#15: Cannot deliver "getPoserInvitation" to target; typeof target is "undefined"

  at fullRevive (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:368:36)
  at Object.unserialize (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:451:19)
  at notifyOnePromise (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:916:19)
  at notify (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:929:7)
  at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1161:11)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
  at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
  at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)

RemoteTypeError(error:liveSlots:v2#70001)#15 ERROR_NOTE: Rejection from: (Error#16) : 379 . 0
RemoteTypeError(error:liveSlots:v2#70001)#15 ERROR_NOTE: Rejection from: (Error#17) : 2 . 1
RemoteTypeError(error:liveSlots:v2#70001)#15 ERROR_NOTE: Sent as error:liveSlots:v3#70002
Nested 2 errors under RemoteTypeError(error:liveSlots:v2#70001)#15
  Error#16: Event: 377.2
  
    at Proxy.eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:39:49)
    at Alleged: root.eval [as bootstrap] (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:263:62)
  
  Error#17: Event: 0.2
  
    at deliver (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:839:28)
    at dispatchToUserspace (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:1156:11)
    at eval (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:39)
    at runWithoutMetering (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:22:14)
    at wrapped (eval at <anonymous> (eval at makeEvaluateFactory (file:///Users/chrishibbert/agoric-sdk/node_modules/ses/dist/ses.umd.js:3305:10)), <anonymous>:40:14)
  
##### KERNEL PANIC: kp40.policy panic: rejected {"body":"{\"@qclass\":\"error\",\"errorId\":\"error:liveSlots:v3#70002\",\"message\":\"Cannot deliver \\\"getPoserInvitation\\\" to target; typeof target is \\\"undefined\\\"\",\"name\":\"TypeError\"}","slots":[]} #####
  zoe - contract governance

  Rejected promise returned by test. Reason:

  Error {
    message: 'kernel panic kp40.policy panic: rejected {"body":"{\\"@qclass\\":\\"error\\",\\"errorId\\":\\"error:liveSlots:v3#70001\\",\\"message\\":\\"vat terminated\\",\\"name\\":\\"Error\\"}","slots":[]}',
  }



  zoe - change electorate

  Rejected promise returned by test. Reason:

  Error {
    message: 'kernel panic kp40.policy panic: rejected {"body":"{\\"@qclass\\":\\"error\\",\\"errorId\\":\\"error:liveSlots:v3#70002\\",\\"message\\":\\"Cannot deliver \\\\\\"getPoserInvitation\\\\\\" to target; typeof target is \\\\\\"undefined\\\\\\"\\",\\"name\\":\\"TypeError\\"}","slots":[]}',
  }

  ─

  2 tests failed

Process finished with exit code 1
```

## To Reproduce

```
cd packages/governance
yarn test test/swingsetTests/contractGovernor/test-governor.js
```

## Etiology guess

I think I was trying to initialize a vat twice. I'll fix that and report if that makes the problem go away.

No, that wasn't it. I fixed the problem by changing the tests to each have **`test.serial()`** in test-governor. After that, the pre-existing test passes as it does when run with `test.only()` and the unfinished one fails.

## Platform Environment
 - what OS are you using? what version of Node.js?
     `Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64`
My node version is v14.17.0

 - is there anything special/unusual about your platform?

 `SWINGSET_WORKER_TYPE=local`

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
     `agoricdev-6-40-ge869e849d`

**Comment by Tartuffo** [comment]
@warner do you know if this was fixed?

**Comment by FUDCo** [comment]
@Chris-Hibbert have you seen any further manifestations of this?  I'm thinking that we should just close this, given that it is known that running multiple GC-sensitive tests concurrently with local workers tends to manifest problems because the GC cycles interleave, and that using `test.serial` tends to fix the problem (as it seems to have done in this case).  But if you have more information to the contrary please speak up.

**Comment by Chris-Hibbert** [comment]
I haven't see anything like this again. I'll close both of these.
