### ISSUE TITLE
Make the link-cli test more stable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#4769]
## What is the Problem Being Solved?

The test "getting started (link-cli)" flakes. I've encountered this several times,
```
2022-03-08T18:00:32.433Z shutdown: Shutting down cleanly...
2022-03-08T18:00:32.435Z shutdown: Process terminated!
REJECTED from ava test: (Error#1)
Error#1: ENOTEMPTY: directory not empty, rmdir '/tmp/agoric-cli-test--3696-7aDkh6Dkrs36/dapp-foo/_agstate/agoric-servers/dev'
  at Object.rmdirSync (fs.js:916:10)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
  at gettingStartedWorkflowTest (packages/agoric-cli/tools/getting-started.js:264:5)

  ✖ workflow Rejected promise returned by test
```
Most recently https://github.com/Agoric/agoric-sdk/runs/5468765128?check_suite_focus=true

## Description of the Design

Not sure. Maybe a force option to rmdir?

## Security Considerations
--
## Test Plan

--

**Comment by Tartuffo** [comment]
@turadg can we delay this to after launch?

**Comment by turadg** [comment]
Sure. I don't remember why you put it in there.

**Comment by turadg** [comment]
Just ran into this again: https://github.com/Agoric/agoric-sdk/actions/runs/10043875356/job/27757620212?pr=9743

It still failed after the three retries. @frazarshad maybe this is the same problem as https://github.com/Agoric/agoric-sdk/issues/9325 but since the failure was in `link-cli` I'm commenting on the issue with that in the title.
