### ISSUE TITLE
Implausible `TypeError: String.prototype.replace: this is undefined`

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#4870]
## Describe the bug
It seems that under some circumstances, delivering a message to an object with the corresponding method missing results in a `TypeError: String.prototype.replace: this is undefined` instead of the normal `TypeError: target has no method`. The stack seem to root this entirely in LiveSlots / SES.

## To Reproduce
1. `git clone --branch mhofman/bug-missing-method-string-replace-error https://github.com/Agoric/testnet-load-generator.git`
2. `SDK_REVISION=ce913b29 ./start.sh --stages=2 --stage.duration=1 --stage.loadgen.vault.interval=300`
4. See error when `getDebtAmount` is sent

## Expected behavior
The normal `TypeError: target has no method` listing the available methods

## Platform Environment
 - what OS are you using? what version of Node.js? Debian 16, Node 16
 - what version of the Agoric-SDK are you using? `ce913b29`

## Relevant output
```
stage-1: chain: 2022-03-22T00:09:53.837Z SwingSet: ls: v21: Logging sent error stack (TypeError#1)
stage-1: chain: 2022-03-22T00:09:53.837Z SwingSet: ls: v21: TypeError#1: String.prototype.replace: this is undefined
stage-1: chain: 2022-03-22T00:09:53.837Z SwingSet: ls: v21: TypeError: String.prototype.replace: this is undefined
stage-1: chain:  at replace ()
stage-1: chain:  at apply ()
stage-1: chain:  at getLogArgs (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1680)
stage-1: chain:  at note (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1789)
stage-1: chain:  at (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10594)
stage-1: chain:  at win (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11294)
stage-1: chain:  at ()
stage-1: chain: 
stage-1: chain: 2022-03-22T00:09:53.837Z SwingSet: ls: v21: TypeError#1 ERROR_NOTE: Sent as error:liveSlots:v21#70001
stage-1: client: 2022-03-22T00:09:54.474Z SwingSet: ls: v14: Logging sent error stack (RemoteTypeError(error:liveSlots:v21#70001)#1)
stage-1: client: 2022-03-22T00:09:54.474Z SwingSet: ls: v14: RemoteTypeError(error:liveSlots:v21#70001)#1: String.prototype.replace: this is undefined
stage-1: client: 2022-03-22T00:09:54.475Z SwingSet: ls: v14: TypeError: String.prototype.replace: this is undefined
stage-1: client:  at makeError (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1740)
stage-1: client:  at fullRevive (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:5530)
stage-1: client:  at unserialize (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:5613)
stage-1: client:  at notifyOnePromise (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14619)
stage-1: client:  at notify (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14632)
stage-1: client:  at dispatchToUserspace (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14880)
stage-1: client:  at runWithoutMetering (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15278)
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.475Z SwingSet: ls: v14: RemoteTypeError(error:liveSlots:v21#70001)#1 ERROR_NOTE: Rejection from: (Error#2) : 14 . 0
stage-1: client: 2022-03-22T00:09:54.475Z SwingSet: ls: v14: RemoteTypeError(error:liveSlots:v21#70001)#1 ERROR_NOTE: Rejection from: (Error#3) : 5 . 3
stage-1: client: 2022-03-22T00:09:54.476Z SwingSet: ls: v14: RemoteTypeError(error:liveSlots:v21#70001)#1 ERROR_NOTE: Sent as error:liveSlots:v14#70001
stage-1: client: 2022-03-22T00:09:54.476Z SwingSet: ls: v14: Error#2: Event: 13.1
stage-1: client: 2022-03-22T00:09:54.476Z SwingSet: ls: v14: Error: Event: 13.1
stage-1: client:  at construct ()
stage-1: client:  at Error (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7595)
stage-1: client:  at trackTurns (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10573)
stage-1: client:  at handle (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11285)
stage-1: client:  at (.../eventual-send/src/E.js:39)
stage-1: client:  at closeVault (.../loadgen-contract/agent-create-vault.js:120)
stage-1: client:  at closeVault ()
stage-1: client:  at doVaultCycle (.../loadgen-contract/agent-create-vault.js:147)
stage-1: client:  at ()
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.477Z SwingSet: ls: v14: Error#3: Event: 4.1
stage-1: client: 2022-03-22T00:09:54.477Z SwingSet: ls: v14: Error: Event: 4.1
stage-1: client:  at construct ()
stage-1: client:  at Error (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7595)
stage-1: client:  at trackTurns (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10573)
stage-1: client:  at handle (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11285)
stage-1: client:  at deliver (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14542)
stage-1: client:  at dispatchToUserspace (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14875)
stage-1: client:  at runWithoutMetering (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15278)
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.563Z SwingSet: vat: v2: Temporary logging of sent error (RemoteTypeError(error:liveSlots:v14#70001)#1)
stage-1: client: 2022-03-22T00:09:54.563Z SwingSet: vat: v2: RemoteTypeError(error:liveSlots:v14#70001)#1: String.prototype.replace: this is undefined
stage-1: client: 2022-03-22T00:09:54.564Z SwingSet: vat: v2: TypeError: String.prototype.replace: this is undefined
stage-1: client:  at makeError (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1740)
stage-1: client:  at fullRevive (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:5530)
stage-1: client:  at unserialize (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:5613)
stage-1: client:  at notifyOnePromise (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14619)
stage-1: client:  at notify (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14632)
stage-1: client:  at dispatchToUserspace (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14880)
stage-1: client:  at runWithoutMetering (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15278)
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.565Z SwingSet: vat: v2: RemoteTypeError(error:liveSlots:v14#70001)#1 ERROR_NOTE: Rejection from: (Error#2) : 227 . 0
stage-1: client: 2022-03-22T00:09:54.565Z SwingSet: vat: v2: RemoteTypeError(error:liveSlots:v14#70001)#1 ERROR_NOTE: Sent as error:captp:http://127.0.0.1#20001
stage-1: client: 2022-03-22T00:09:54.565Z SwingSet: vat: v2: Error#2: Event: 226.1
stage-1: client: 2022-03-22T00:09:54.565Z SwingSet: vat: v2: Error: Event: 226.1
stage-1: client:  at construct ()
stage-1: client:  at Error (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7595)
stage-1: client:  at trackTurns (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10573)
stage-1: client:  at handle (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11285)
stage-1: client:  at CTP_CALL (.../captp/src/captp.js:432)
stage-1: client:  at CTP_CALL ()
stage-1: client:  at dispatch (.../captp/src/captp.js:573)
stage-1: client:  at onMessage (.../solo/src/captp.js:74)
stage-1: client:  at onMessage ()
stage-1: client:  at apply ()
stage-1: client:  at apply ()
stage-1: client:  at dispatchToHandler (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10951)
stage-1: client:  at (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10589)
stage-1: client:  at win (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11294)
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.566Z SwingSet: vat: v2: Error#2 ERROR_NOTE: Caused by: (Error#3)
stage-1: client: 2022-03-22T00:09:54.566Z SwingSet: vat: v2: Error#3: Event: 225.1
stage-1: client: 2022-03-22T00:09:54.566Z SwingSet: vat: v2: Error: Event: 225.1
stage-1: client:  at construct ()
stage-1: client:  at Error (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7595)
stage-1: client:  at trackTurns (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10573)
stage-1: client:  at handle (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11285)
stage-1: client:  at inbound (.../solo/src/vat-http.js:193)
stage-1: client:  at inbound ()
stage-1: client:  at apply ()
stage-1: client:  at apply ()
stage-1: client:  at dispatchToHandler (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10951)
stage-1: client:  at (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10589)
stage-1: client:  at win (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11294)
stage-1: client:  at ()
stage-1: client: 
stage-1: client: 2022-03-22T00:09:54.566Z SwingSet: vat: v2: Error#3 ERROR_NOTE: Caused by: (Error#4)
stage-1: client: 2022-03-22T00:09:54.567Z SwingSet: vat: v2: Error#4: Event: 224.1
stage-1: client: 2022-03-22T00:09:54.567Z SwingSet: vat: v2: Error: Event: 224.1
stage-1: client:  at construct ()
stage-1: client:  at Error (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7595)
stage-1: client:  at trackTurns (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:10573)
stage-1: client:  at handle (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:11285)
stage-1: client:  at deliver (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14542)
stage-1: client:  at dispatchToUserspace (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14875)
stage-1: client:  at runWithoutMetering (/workspaces/agoric/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15278)
stage-1: client:  at ()
stage-1: client: 
stage-1: loadgen: CapTP bundle exception: (RemoteTypeError(error:captp:http://127.0.0.1#20001)#1)
stage-1: loadgen: RemoteTypeError(error:captp:http://127.0.0.1#20001)#1: String.prototype.replace: this is undefined
stage-1: loadgen: 
stage-1: loadgen:   at WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:117:13)
stage-1: loadgen:   at WebSocket.emit (events.js:400:28)
stage-1: loadgen:   at WebSocket.emit (domain.js:475:12)
stage-1: loadgen:   at Receiver.emit (events.js:400:28)
stage-1: loadgen:   at Receiver.emit (domain.js:475:12)
stage-1: loadgen:   at Socket.emit (events.js:400:28)
stage-1: loadgen:   at Socket.emit (domain.js:475:12)
stage-1: loadgen: 
stage-1: loadgen: RemoteTypeError(error:captp:http://127.0.0.1#20001)#1 ERROR_NOTE: Rejection from: (Error#2) : 32 . 0
stage-1: loadgen: Nested error under RemoteTypeError(error:captp:http://127.0.0.1#20001)#1
stage-1: loadgen:   Error#2: Event: 31.1
stage-1: loadgen:   
stage-1: loadgen:     at Object.vaultCycle [as cycle] (/workspaces/agoric/testnet-load-generator/loadgen/task-create-vault.js:58:24)
stage-1: loadgen:     at maybeStartOneCycle (/workspaces/agoric/testnet-load-generator/loadgen/loop.js:81:6)
stage-1: loadgen:     at bump (/workspaces/agoric/testnet-load-generator/loadgen/loop.js:152:7)
stage-1: loadgen:     at Timeout.start [as _onTimeout] (/workspaces/agoric/testnet-load-generator/loadgen/loop.js:157:7)
stage-1: loadgen:   
stage-1: loadgen: [vault] failed: (RemoteTypeError(error:captp:http://127.0.0.1#20001)#1)
```

**Comment by mhofman** [comment]
Updated issue description and branch. Now built on top of the in review loadgen PR (https://github.com/Agoric/testnet-load-generator/pull/71), and verified on latest `agoric-sdk` master.

**Comment by mhofman** [comment]
I am perplexed as I can no longer reproduce the expected "no method" error with a simple change as I though I was the other day. I tried re-using the original commits of both the loadgen and sdk, without luck.

For reference, here is the original commit of the loadgen when this issue was originally filed: https://github.com/Agoric/testnet-load-generator/tree/mhofman/bug-missing-method-string-replace-error-initial

**Comment by mhofman** [comment]
When trying to add a `try` / `catch` in `getLogArgs` to get an idea of the shape of the args, the problem does not reproduce, so this smells like a GC bug in XS. Given that we have a restart / non-restart based repro on #4911, I'd venture to say this is related to reloading from a snapshot.

**Comment by kriskowal** [comment]
I see you’re no longer able to repro. Is this still a valid issue? @mhofman

**Comment by mhofman** [comment]
Very much so. I'm validating a fix received from moddable however.

**Comment by mhofman** [comment]
I've verified the patch from moddable fixes this issue! Once we update to the new (TBD) SDK, we should be able to close this issue.
