### ISSUE TITLE
Liquidation failure causes infinite reattempts

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#5100]
## To Reproduce
1. Change the `liquidate` function in liquidation.js to `throw`
2. run vault automated tests

Alternatively, add the throw in the liquidateMinimum contract. Same result.

## Expected behavior
TBD, but not infinite loop

## Platform Environment
agoric-sdk

## Additional context
```
liquidateAndRemove failed with (Error#811)
Error#811: Vault cannot transition from liquidating to liquidating
  at assignPhase (.../run-protocol/src/vaultFactory/vault.js:203:1)
  at Alleged: InnerVault helper.method [as assignPhase] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at liquidating (.../run-protocol/src/vaultFactory/vault.js:582:8)
  at Alleged: InnerVault self.method [as liquidating] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at liquidate (.../run-protocol/src/vaultFactory/liquidation.js:57:12)
  at liquidateAndRemove (.../run-protocol/src/vaultFactory/vaultManager.js:331:8)
  at Alleged: VaultManagerKit helper.method [as liquidateAndRemove] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at reschedulePriceCheck (.../run-protocol/src/vaultFactory/vaultManager.js:315:26)

liquidateAndRemove failed with (Error#812)
Error#812: Vault cannot transition from liquidating to liquidating
  at assignPhase (.../run-protocol/src/vaultFactory/vault.js:203:1)
  at Alleged: InnerVault helper.method [as assignPhase] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at liquidating (.../run-protocol/src/vaultFactory/vault.js:582:8)
  at Alleged: InnerVault self.method [as liquidating] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at liquidate (.../run-protocol/src/vaultFactory/liquidation.js:57:12)
  at liquidateAndRemove (.../run-protocol/src/vaultFactory/vaultManager.js:331:8)
  at Alleged: VaultManagerKit helper.method [as liquidateAndRemove] (packages/SwingSet/src/liveslots/virtualObjectManager.js:465:43)
  at reschedulePriceCheck (.../run-protocol/src/vaultFactory/vaultManager.js:315:26)
```

**Comment by dtribble** [comment]
Dup of #5045
