### ISSUE TITLE
ceaseRecognition misparses vrefs (was: Consensus failure: missing v7.source)

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5113]
## Describe the bug

I ran into this stacktrace while simulating a multi-node validator setup.  To note - this was on arm64

On docker image 20220409151630ea4c85

Cluster setup:
3 validators
8 ag-solos

```
6:19PM INF received complete proposal block hash=2A48FAEBFE1693E607159809126F7EFD4265247BF24115405C91D8D820159DCA height=51 module=consensus
6:19PM INF finalizing commit of block hash=2A48FAEBFE1693E607159809126F7EFD4265247BF24115405C91D8D820159DCA height=51 module=consensus num_txs=1 root=8AC2E0CA6970964A04CC5BACA12DAC7A65441F1DD0CF42677E152180BB2F4451
2022-04-14T18:19:24.969Z block-manager: block 51 begin
2022-04-14T18:19:25.064Z SwingSet: kernel: error in kernel.deliver: (Error#1)
Error#1: missing: v7.source

  at getRequired (.../swingset-vat/src/kernel/state/vatKeeper.js:92:1)
  at Object.getSourceAndOptions (.../swingset-vat/src/kernel/state/vatKeeper.js:113:25)
  at ensureVatOnline (.../swingset-vat/src/kernel/vat-warehouse.js:112:33)
  at Object.deliverToVat (.../swingset-vat/src/kernel/vat-warehouse.js:268:22)
  at runMicrotasks (<anonymous>)
  at async deliverAndLogToVat (.../swingset-vat/src/kernel/kernel.js:364:22)

2022-04-14T18:19:25.064Z block-manager: END_BLOCK error: (Error#1)
portHandler threw (Error#1)
6:19PM ERR CONSENSUS FAILURE!!! err="Error: missing: v7.source" module=consensus stack="goroutine 168 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x88\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0x4000c7f500, 0xffff87104340)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:726 +0x48\npanic({0xffff86eb46e0, 0x4003592c50})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x21c\ngithub.com/Agoric/agoric-sdk/golang/cosmos/x/swingset.EndBlock({{0xffff87168948, 0x400013c020}, {0xffff8718ff20, 0x400128fd40}, {{0xb, 0x0}, {0x4000049bd0, 0xa}, 0x33, {0x24080e42, ...}, ...}, ...}, ...)\n\t/usr/src/agoric-sdk/golang/cosmos/x/swingset/abci.go:69 +0x334\ngithub.com/Agoric/agoric-sdk/golang/cosmos/x/swingset.AppModule.EndBlock({{}, {{0xffff87137d90, 0x40005b1490}, {0xffff87194698, 0x40001da640}, {{0xffff8718bc38, 0x40001da640}, 0x40000aa1b8, {0xffff87137d90, 0x40005b1340}, ...}, ...}}, ...)\n\t/usr/src/agoric-sdk/golang/cosmos/x/swingset/module.go:130 +0x70\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(0x40005c2380, {{0xffff87168948, 0x400013c020}, {0xffff8718ff20, 0x400128fd40}, {{0xb, 0x0}, {0x4000049bd0, 0xa}, 0x33, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.3/types/module/module.go:499 +0x340\ngithub.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).EndBlocker(...)\n\t/usr/src/agoric-sdk/golang/cosmos/app/app.go:722\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0x40005ef040, {0x33})\n\t/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.3/baseapp/abci.go:213 +0x2d4\ngithub.com/tendermint/tendermint/abci/client.(*committingClient).EndBlockSync(0x400137d740, {0x33})\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/abci/client/committing_client.go:339 +0xf8\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0x4000cbc990, {0x33})\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/proxy/app_conn.go:89 +0x3c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0xffff871696d8, 0x4000f185a0}, {0xffff8717c330, 0x4000cbc990}, 0x40034e03c0, {0xffff8718a060, 0x4000e07130}, 0x1)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/state/execution.go:327 +0x4b0\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0x4000c0d110, {{{0xb, 0x0}, {0x400117a690, 0x7}}, {0x400117a6a0, 0xa}, 0x1, 0x32, {{0x4004b7ba60, ...}, ...}, ...}, ...)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/state/execution.go:140 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x4000c7f500, 0x33)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:1635 +0x96c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x4000c7f500, 0x33)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:1546 +0x330\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0x4000c7f500, 0x0, 0x33)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:1481 +0x94\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x4000c7f500, 0x33, 0x0)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:1519 +0xc40\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x4000c7f500, 0x4003f38dc0, {0x40016854d0, 0x28})\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:2132 +0xc54\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x4000c7f500, 0x4003f38dc0, {0x40016854d0, 0x28})\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:1930 +0x40\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x4000c7f500, {{0xffff8712a1e0, 0x4002ddf290}, {0x40016854d0, 0x28}})\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:838 +0x39c\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x4000c7f500, 0x0)\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:762 +0x324\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:378 +0x120\n"
```

Slogs and ag-cosmos-chain-state from all validators: https://drive.google.com/drive/folders/14GM1sQdIYBG5XGwTWwsujff9uCCba-Ev?usp=sharing

**Comment by warner** [comment]
I'm looking at the slogs, it seems that v7 was terminated at crankNum 9193 for "invalid vref (a string)". So the first bug is: why was it killed?

The second bug is that something is trying to send a message to the dead vat, and instead of rejecting the message with the usual "vat terminated" error, we're trying to deliver it. That tells vat-warehouse to spin it up, but of course we've deleted all traces of the vat during termination, so there's no `.source` entry (or anything else).

**Comment by warner** [comment]
The immediate cause of the vat termination was a bad `retireImports`, still not sure what the root cause was:

```json
{"time":1649960360.2835531,"type":"deliver","crankNum":9193,"vatID":"v7","deliveryNum":993,"replay":false,"kd":["retireImports",["ko472"]],"vd":["retireImports",["o-154"]]}
{"time":1649960360.2838955,"type":"console","state":"delivery","crankNum":9193,"vatID":"v7","deliveryNum":993,"level":"error","args":["error Error: invalid vref (a string) during vat dispatch() of retireImports,o-154"]}
{"time":1649960360.2853122,"type":"deliver-result","crankNum":9193,"vatID":"v7","deliveryNum":993,"replay":false,"dr":["error","invalid vref (a string)",{"meterType":"xs-meter-13","currentHeapCount":112855,"compute":14917,"allocate":46268
448}]}
```

**Comment by warner** [comment]
Ari says this is commit ID ea4c85c624e1e4e71f0398763db7a804adedc260 , which predates @FUDCo's recent "keep collection membership info in DB" PR (#5059).

That object (`o-154`) was a `SeatHandleHandle`, imported during a dispatch.deliver of `makeNoEscrowSeat()` during delivery 976 / crank 9098. On the next BOYD delivery (977 / crank 9100), the vat checked the refcount (`vom.rc.o-154`, key missing so refcount=0) and emitted a `dropImports(o-154)` (but not a `retireImports`).

340ms later (delivery 993 / crank 9193) the vat was given a `dispatch.retireImports(['o-154'])`, which triggered the "invalid vref" message. The assert `details` censoring means I can't see what the vref was in the slogfile (poking @erights about this frequent complaint), it was probably printed to stderr if we can find a copy of that and figure out how to correlate it with this message. Stderr might also tell us the stack trace for that error, which could help me pin down where in liveslots was creating it.

The "invalid vref" message is only emitted by `parseVatSlots()`, possibly by the `assert(!parseVatSlog(vref).allocatedByVat)` call in the preamble to `retireImports`, but the slogfile seems to have a sound argument.

`retireImports` calls `ceaseRecognition(vref)`, which does it's own `parseVatSlot()` at startup. If the object being retired had facets, `ceaseRecognition(vref)` recurses with each facet (calling e.g. `ceaseRecognition(vref:0)`), so perhaps one of the facets vrefs it creates might fail the `parseVatSlot` check. cc @FUDCo 

I think we'll need the stderr to find out what the vref was and which `parseVatSlot` complained about it.

**Comment by warner** [comment]
We tracked this down to `virtualReferences.js > ceaseRecognition()` being confused about the nature of the vref it received. With more tracing, we learned that the failing `parseVatSlot` call was given a vref of `o-154:0:0`, which is broken in two ways: there should be at most one facetID extension (the `:0` suffix), and the `o-` indicates an *import*, which should never be a virtual object instance (which are the only things that can have facets).

```
2022-04-14T22:00:27.763Z SwingSet: ls: v7: ls dispatch error: (Error#1)
2022-04-14T22:00:27.763Z SwingSet: ls: v7: Error#1: invalid vref o-154:0:0
2022-04-14T22:00:27.763Z SwingSet: ls: v7: Error: invalid vref (a string)
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:7062)
 at makeError (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1207)
 at fail (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1335)
 at baseAssert (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:1353)
 at parseVatSlot (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:6723)
 at ceaseRecognition (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:7329)
 at ceaseRecognition (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:7346)
 at ceaseRecognition (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:7346)
 at forEach ()
 at retireImports (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:14908)
 at dispatchToUserspace (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15147)
 at runWithoutMetering (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15547)
 at ()

2022-04-14T22:00:27.763Z SwingSet: vat: v7: error Error: invalid vref (a string) during vat dispatch() of retireImports,o-154
2022-04-14T22:00:27.765Z SwingSet: kernel: delivery problem, terminating vat v7 invalid vref (a string)
```

We think that the vat code defined a Kind which received a KindID of `154`. All instances of this kind will get vrefs like `o+154/1` and `o+154/2`.

Then, we think the vat received enough imports for one of them to be assigned `o-154`. This imported Presence was held briefly, then dropped. Shortly thereafter, the original exporter retired the object, causing the kernel to tell our vat `dispatch.retireImports(['o-154'])`. This vectors into `ceaseRecognition('o-154')`:

```js
  function ceaseRecognition(vref) {
    let doMoreGC = false;
    const { id, facet } = parseVatSlot(vref);
    if (facet === undefined) {
      // If `vref` identifies a multi-faceted object that should no longer be
      // "recognized", what that really means that all references to its
      // individual facets should no longer be recognized -- nobody actually
      // references the object itself except internal data structures.  So in
      // this case we need individually to stop recognizing the facets
      // themselves.
      const kindInfo = kindInfoTable.get(`${id}`);
      // This function can be called either from `dispatch.retireImports` or
      // from `possibleVirtualObjectDeath`.  In the latter case the vref is
      // actually a baseRef and so needs to be expanded to cease recognition of
      // all the facets.
      if (kindInfo) {
        const { facetNames } = kindInfo;
        if (facetNames) {
          for (let i = 0; i < facetNames.length; i += 1) {
            const more = ceaseRecognition(`${vref}:${i}`);
            doMoreGC = doMoreGC || more;
          }
          return doMoreGC;
        }
      }
    }
```

which parses `o-154` into `{ id: 154, facet: undefined }`, but note that it does not look at `allocatedByVat` or `virtual`. It assumed that the vref was `o+154/NN`, looked up `154` in `kindInfoTable` and found a match, and decided that it was a whole cohort getting retired, so it looked up the `facetNames` and started recursing into what it thought was `ceaseRecognition('o+154/NN:0')`, `o+154/NN:1`, etc.

But in fact it called `ceaseRecognition('o-154:0')`, which failed in the same way, and recursed to `o-154:0:0`, at which point `parseVatSlot` threw up its hands and `assert`ed out of there.

The quickest fix will be for `ceaseRecognition` to replace the `if (facet === undefined)` with:

```js
    const p = parseVatSlot(vref);
    if (p.allocatedByVat && p.virtual && p.facet === undefined) {
```

A deeper fix would be for `kindInfoTable` to be indexed by the full baseRef (`o+154`) instead of merely the ID (`154`).

To write a test for this, we'd need to force a collision between the kernel-allocated import ID and the liveslots-allocated export/kind ID. I'm not sure what would be a good way to pull that off.. maybe have the vat keep creating Kinds and exporting an instance until the test program sees the numbers collide with a similarly-repeated import.

Or, better, we need a unit test that only executes `ceaseRecognition`, and calls it with a variety of vrefs.

**Comment by FUDCo** [comment]
> A deeper fix would be for `kindInfoTable` to be indexed by the full baseRef (`o+154`) instead of merely the ID (`154`).

The `kindInfoTable` is a table of information about kinds, not a table of information about objects or baserefs.  For various reasons it really wants to be indexed by the kind ID and not a baseRef that happens to incorporate the kind ID.  The fix you outlined is the actual correct fix.
