### ISSUE TITLE
slog-to-otel outdated by change from method+args to methargs

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5445]
## Description

Starting xnet (#5375) failed in `slog-to-otel.js`.

## To Reproduce

try to start a node with telemetry (`SLOGSENDER=@agoric/telemetry/src/otel-trace.js`).

## Platform Environment

instagoric a98368e

## Symptoms

```
022-05-26T20:05:44.876Z block-manager: block bootstrap
Unknown crank-start message.type startVat
Unknown crank-start message.type startVat
Unknown crank-start message.type startVat
Unknown crank-start message.type startVat
Unknown crank-start message.type startVat
Error tracing slog: {
  time: 1653595544.8906558,
  type: 'crank-start',
  message: {
    type: 'send',
    target: 'ko21',
    msg: { methargs: [Object], result: 'kp40' }
  }
} (TypeError#1)
TypeError#1: Cannot read property 'slots' of undefined

  at extractMessageAttrs (packages/telemetry/src/slog-to-otel.js:107:60)
  at slogSender (packages/telemetry/src/slog-to-otel.js:596:43)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:633:7)
  at writeSlogObject (packages/SwingSet/src/controller/controller.js:222:7)
  at Object.write (.../swingset-vat/src/kernel/slogger.js:111:27)
  at processAcceptanceMessage (.../swingset-vat/src/kernel/kernel.js:1103:12)
  at tryProcessMessage (.../swingset-vat/src/kernel/kernel.js:1095:8)
  at Object.run (.../swingset-vat/src/kernel/kernel.js:1518:25)
  at async crankScheduler (packages/cosmic-swingset/src/kernel-stats.js:315:5)
  at async bootstrapBlock (packages/cosmic-swingset/src/launch-chain.js:235:5)
  at async blockingSend (packages/cosmic-swingset/src/block-manager.js:144:9)
  at async portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:215:16)

portHandler threw (TypeError#1)
```

reporting on behalf of @michaelfig 
cc @arirubinstein @warner  @FUDCo @Tartuffo

**Comment by mhofman** [comment]
As mentioned offline, we should enable the otel telemetry in the deployment integration test.

**Comment by michaelfig** [comment]
Still an issue on `agoricdevnet-13`: 

```
Error tracing slog: {
  time: 1653939220.277996,
  type: 'crank-start',
  message: {
    type: 'send',
    target: 'ko25',
    msg: { methargs: [Object], result: null }
  }
} (TypeError#1)
TypeError#1: Cannot read properties of undefined (reading 'slots')

  at extractMessageAttrs (packages/telemetry/src/slog-to-otel.js:107:60)
  at slogSender (packages/telemetry/src/slog-to-otel.js:596:43)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:633:7)
  at writeSlogObject (packages/SwingSet/src/controller/controller.js:222:7)
  at Object.write (.../swingset-vat/src/kernel/slogger.js:111:27)
  at processAcceptanceMessage (.../swingset-vat/src/kernel/kernel.js:1103:12)
  at tryProcessMessage (.../swingset-vat/src/kernel/kernel.js:1095:8)
  at Object.run (.../swingset-vat/src/kernel/kernel.js:1518:25)
  at Object.run (packages/SwingSet/src/controller/controller.js:395:21)
  at crankScheduler (packages/cosmic-swingset/src/kernel-stats.js:315:22)
  at endBlock (packages/cosmic-swingset/src/launch-chain.js:253:11)
  at processAction (packages/cosmic-swingset/src/block-manager.js:110:13)
  at blockingSend (packages/cosmic-swingset/src/block-manager.js:234:17)
  at async portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:215:16)
```

**Comment by michaelfig** [comment]
Nevermind.  My mistake using an outdated container.
