### ISSUE TITLE
`agd` should exit with error code on concensus failure

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5462]
## Describe the bug
While investigating a [consensus failure in a CI job](https://github.com/Agoric/agoric-sdk/runs/6633516162?check_suite_focus=true#step:10:4949), I noticed that the local-chain process started by the loadgen exited without an error code, causing the loadgen monitor to keep going until it timedout.

## To Reproduce
Trigger consensus failure

## Expected behavior
A non 0 exit code

## Platform Environment
CI docker image

## Screenshots
```
stage-0: chain: 12:54AM ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.AppHash.  Expected E33674E6D2E2E299D519527484F3048CE4E624C68F4696FE0346594CD3CFD138, got 75C787F384C95030BC5DE83785CE8E294FB60ADB10B0B2ADFD8D1C425BB158D3" height=76 module=consensus round=0
stage-0: chain: 12:54AM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected E33674E6D2E2E299D519527484F3048CE4E624C68F4696FE0346594CD3CFD138, got 75C787F384C95030BC5DE83785CE8E294FB60ADB10B0B2ADFD8D1C425BB158D3" module=consensus stack="goroutine 588 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/runner/go/pkg/mod/github.c...c0001d4a80, {{0x7fe6d30aa720, 0xc002996610}, {0xc000f1dec0, 0x0}})\n\t/home/runner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:838 +0x40b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0001d4a80, 0x0)\n\t/home/runner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:762 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/home/runner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.14-alpha.agoric.1/consensus/state.go:378 +0x12f\n"
stage-0: chain: 12:54AM INF Stopping baseWAL service impl={"Logger":{}} module=consensus wal=/home/runner/.ag-chain-cosmos/data/cs.wal/wal
stage-0: chain: 12:54AM INF Stopping Group service impl={"Dir":"/home/runner/.ag-chain-cosmos/data/cs.wal","Head":{"ID":"XcorDBaT4wZM:/home/runner/.ag-chain-cosmos/data/cs.wal/wal","Path":"/home/runner/.ag-chain-cosmos/data/cs.wal/wal"},"ID":"group:XcorDBaT4wZM:/home/runner/.ag-chain-cosmos/data/cs.wal/wal","Logger":{}} module=consensus wal=/home/runner/.ag-chain-cosmos/data/cs.wal/wal
stage-0: chain: Chain exited successfully
```

**Comment by michaelfig** [comment]
Yeah, after you `start` it should never exit successfully.  I believe I've fixed that in the above PR.
