### ISSUE TITLE
Loadgen experienced suspicious XS `fatal!` errors

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5976]
## Describe the bug

Sometime after https://github.com/Agoric/agoric-sdk/commit/00d565d7fa87c55f849825aed5c26b43cd9a82d4, the loadgen on the benchmark machine started experiencing SIGABRT caused by `xsMemory.c:303: fatal!` and `xsType.c:546: fatal!` errors. This would happen in the first block after a node restart. Unfortunately the exact commit where this started is unknown since another issue (https://github.com/Agoric/agoric-sdk/issues/5911) prevented to get that far on restarts.

It got seemingly resolved between https://github.com/Agoric/agoric-sdk/compare/e7e652986cb5410bc09152b8974d6c60cfbb0b28...914fc4c5a31f10207f99aa86e02e0d430b198fcb, but none of these are code changes. I suppose a dependency change in https://github.com/Agoric/agoric-sdk/pull/5895 may have had an impact?

## To Reproduce
Check loadgen logs

## Expected behavior
No XS fatal errors

## Additional context
```
0 4700232 daily-perf-914fc4c5a31f 2022-08-08 22:33:27.457786812 +0000 3
2 4338484 daily-perf-e7e652986cb5 2022-08-08 01:33:10.085955968 +0000 3
2 3292188 daily-perf-cf97ba310fb5 2022-08-07 06:35:13.590091804 +0000 3
2 486812 daily-perf-a679fa561bb6 2022-08-06 09:50:07.074302811 +0000 3 // xsMemory failure related SIGABRT
2 514808 daily-perf-aff48fd1b5c0 2022-08-06 07:26:17.261245675 +0000 3 // actionQueue.tail related SIGABRT
2 514356 daily-perf-f5cf38e954ee 2022-08-06 05:02:19.948927865 +0000 3
2 514800 daily-perf-74885306b09d 2022-08-06 02:38:41.157575496 +0000 3
2 512664 daily-perf-7f294a69eeae 2022-08-05 08:28:13.577604859 +0000 3 // actionQueue.tail related SIGABRT
0 4695976 daily-perf-00d565d7fa87 2022-08-05 06:03:56.213017691 +0000 236
```

`a679fa561bb6` logs:
```
stage-2: chain: 2022-08-06T09:48:23.698Z block-manager: block 570 begin
stage-2: runner: Chain ready
stage-2: chain: 2022-08-06T09:48:23.706Z launch-chain: polled; blockTime:1659774050, h:570; ADDED = false
stage-2: chain: 2022-08-06T09:48:23.711Z launch-chain: mboxDeliver:   ADDED messages
stage-2: monitor-slog: begin-block 570
stage-2: chain: 2022-08-06T09:48:24.085Z SwingSet: vat: v16: bank balance update { address: 'agoric1v0gx5hyhmlf9tqjqk8w80q6snn2n4lmyx8wca8', amount: '18993215255', denom: 'uist' }
stage-2: chain: 9:48AM INF minted coins from module account amount= from=vbank module=x/bank
stage-2: chain: 9:48AM INF minted coins from module account amount=9uist from=vbank module=x/bank
stage-2: chain: /src/packages/xsnap/moddable/xs/sources/xsMemory.c:303: fatal!
stage-2: chain: 2022-08-06T09:48:24.383Z SwingSet: kernel: error in kernel.deliver: (ExitCode#1)
stage-2: chain: ExitCode#1: v29:zcf exited: unknown error
stage-2: chain:
stage-2: chain:   at new ErrorCode (packages/xsnap/api.js:49:5)
```

`cf97ba310fb5` logs:
```
stage-8: chain: 2022-08-07T06:29:35.265Z block-manager: block 10082 begin
stage-8: runner: Chain ready
stage-8: chain: 2022-08-07T06:29:35.271Z launch-chain: polled; blockTime:1659851829, h:10082; ADDED = false
stage-8: monitor-slog: begin-block 10082
stage-8: chain: 2022-08-07T06:29:35.521Z SwingSet: ls: v28: Logging sent error stack (TypeError#1070)
stage-8: chain: 2022-08-07T06:29:35.522Z SwingSet: ls: v28: TypeError#1070: target has no method getDebtAmount , has [ 'getCollateralAmount', 'getCurrentDebt', 'getNormalizedDebt', 'getSubscriber', 'makeAdjustBalancesInvitation', 'makeCloseInvitation', 'makeTransferInvitation' ]
stage-8: chain: 2022-08-07T06:29:35.522Z SwingSet: ls: v28: TypeError: target has no method "getDebtAmount", has ["getCollateralAmount","getCurrentDebt","getNormalizedDebt","getSubscriber","makeAdjustBalancesInvitation","makeCloseInvitation","makeTransferInvitation"]
stage-8: chain:  at makeError (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2717)
stage-8: chain:  at fail (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2844)
stage-8: chain:  at localApplyMethod (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9140)
stage-8: chain:  at apply ()
stage-8: chain:  at dispatchToHandler (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9357)
stage-8: chain:  at (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8972)
stage-8: chain:  at win (/src/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9697)
stage-8: chain:  at ()
stage-8: chain:
stage-8: chain: 2022-08-07T06:29:35.523Z SwingSet: ls: v28: TypeError#1070 ERROR_NOTE: Sent as error:liveSlots:v28#71070
stage-8: chain: 6:29AM INF burned tokens from module account amount=101591898uist from=vbank module=x/bank
stage-8: chain: /src/packages/xsnap/moddable/xs/sources/xsMemory.c:303: fatal!
stage-8: chain: 2022-08-07T06:29:36.136Z SwingSet: kernel: error in kernel.deliver: (ExitCode#1)
stage-8: chain: ExitCode#1: v7:zoe exited: unknown error
stage-8: chain:
stage-8: chain:   at new ErrorCode (packages/xsnap/api.js:49:5)
```

`e7e652986cb5` logs:
```
stage-10: chain: 2022-08-08T01:26:38.028Z block-manager: block 13028 begin
stage-10: runner: Chain ready
stage-10: chain: 2022-08-08T01:26:38.040Z launch-chain: polled; blockTime:1659920249, h:13028; ADDED = false
stage-10: chain: 2022-08-08T01:26:38.044Z launch-chain: mboxDeliver:   ADDED messages
stage-10: monitor-slog: begin-block 13028
stage-10: chain: /src/packages/xsnap/moddable/xs/sources/xsType.c:546: fatal!
stage-10: chain: 2022-08-08T01:26:38.438Z SwingSet: kernel: error in kernel.deliver: (ExitCode#1)
stage-10: chain: ExitCode#1: v7:zoe exited: unknown error
stage-10: chain:
stage-10: chain:   at new ErrorCode (packages/xsnap/api.js:49:5)
stage-10: chain:   at ChildProcess.<anonymous> (packages/xsnap/src/xsnap.js:129:22)
```

**Comment by mhofman** [comment]
I'll try to use `replay-transcripts` to reproduce from the slog+snapshot, and see if not restarting the worker would have prevented the issue, in which case it would point to a problem in xsnap's snapshot logic.

**Comment by mhofman** [comment]
Adding must-have labels since I believe this is a transient bug in XS Snapshots

**Comment by mhofman** [comment]
This is still an issue and recently occurred on revisions 02f2002a41a8 and d8ede9110505 of the daily loadgen.

**Comment by mhofman** [comment]
I provided Moddable a reproduction extracted from the slogs of the failed loadgen on commit 6b7b997439c8. If we skip the reload corresponding to the restart between stage 0 and 1, the snapshots diverge at the subsequent snapshot (at delivery 402) in the order of some string slots. The running hypothesis is that restoring from snapshot causes some internal structure to be recreated in a different order, culminating in a crash. This may be related to #6022 which sees internal promise reactions being randomly fired in a different order after restart.
