### ISSUE TITLE
Error on Instagoric Boot

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6168]
code: [0a3bf20](https://github.com/Agoric/agoric-sdk/commit/0a3bf204e3764e8af30574e0b8204ed8e25e6909)

```
2022-09-09T04:46:10.909Z block-manager: block bootstrap
2022-09-09T04:46:12.741Z SwingSet: xsnap: v1: error during vat dispatch() of startVat,[object Object] (Error#1)
2022-09-09T04:46:12.742Z SwingSet: xsnap: v1: Error#1: copyArray [] - Must be a copyRecord
2022-09-09T04:46:12.743Z SwingSet: xsnap: v1: Error: copyArray (an object) - Must be a copyRecord
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:6160)
 at makeError (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2717)
 at fail (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2844)
 at baseAssert (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:2862)
 at assertChecker (.../marshal/src/helpers/passStyle-helpers.js:52)
 at checkMatches (.../store/src/patterns/patternMatchers.js:1083)
 at fit (.../store/src/patterns/patternMatchers.js:481)
 at buildRootObject (.../vats/src/core/boot-psm.js:113)
 at startVat (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:19186)
 at ()
 at ()

2022-09-09T04:46:12.756Z SwingSet: kernel: ##### KERNEL PANIC: critical vat v1 failed #####
portHandler threw (Error#1)
Error#1: {"@qclass":"error","name":"Error","message":"Error: copyArray (an object) - Must be a copyRecord"}

  at terminateVat (.../swingset-vat/src/kernel/kernel.js:282:39)
  at processDeliveryMessage (.../swingset-vat/src/kernel/kernel.js:1290:7)
  at async tryProcessMessage (.../swingset-vat/src/kernel/kernel.js:1323:14)
  at async Object.run (.../swingset-vat/src/kernel/kernel.js:1777:19)
  at async crankScheduler (packages/cosmic-swingset/src/kernel-stats.js:315:5)
  at async bootstrapBlock (packages/cosmic-swingset/src/launch-chain.js:238:5)
  at async blockingSend (packages/cosmic-swingset/src/block-manager.js:188:9)
  at async portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:235:16)

panic: Error: {"@qclass":"error","name":"Error","message":"Error: copyArray (an object) - Must be a copyRecord"}
```

**Comment by arirubinstein** [comment]
https://github.com/Agoric/instagoric/blob/main/bases/shared/resources/economy-proposals.json
