### ISSUE TITLE
In Econ UI, if there is an active proposal, the History tab fails to load

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#6374]
## Describe the bug
After making a proposal, while it's in the voting period, the History tab does not load
Once the proposal passes however, the information is populated as expected.

When making another proposal after the first proposal passes, this behavior is triggered again.

## To Reproduce
1. Create a proposal and vote on it from two addresses
2. Click on History, and the page is blank
3. wait for proposal to pass, and then page loads

<details>
<summary>console log</summary>

```
bridged bridge received CustomEvent {isTrusted: false, detail: {…}, type: 'message', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
index.b8b4803d.js:17 {status: 'received', data: {…}}
index.b8b4803d.js:17 ProposeParamChange {data: {…}, paramPatch: {…}}
index.b8b4803d.js:17 bridged bridge received CustomEvent {isTrusted: false, detail: {…}, type: 'message', target: agoric-iframe-messenger, currentTarget: agoric-iframe-messenger, …}
index.b8b4803d.js:17 {status: 'received', data: {…}}
index.b8b4803d.js:17 ProposeParamChange {data: {…}, paramPatch: {…}}
index.b8b4803d.js:17 (TypeError#2)
error @ index.b8b4803d.js:17
Mi @ index.b8b4803d.js:51
Oi.nn.callback @ index.b8b4803d.js:51
ih @ index.b8b4803d.js:49
lk @ index.b8b4803d.js:51
jk @ index.b8b4803d.js:51
ik @ index.b8b4803d.js:51
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:15 TypeError#2: Cannot read properties of undefined (reading 'question')
Zn @ index.b8b4803d.js:15
Hn @ index.b8b4803d.js:15
error @ index.b8b4803d.js:17
Mi @ index.b8b4803d.js:51
Oi.nn.callback @ index.b8b4803d.js:51
ih @ index.b8b4803d.js:49
lk @ index.b8b4803d.js:51
jk @ index.b8b4803d.js:51
ik @ index.b8b4803d.js:51
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:17   at https://econ-gov.inter.trade/assets/index.b8b4803d.js:147:1531
  at Array.map (<anonymous>)
  at VotePanel$1 (https://econ-gov.inter.trade/assets/index.b8b4803d.js:147:1414)
  at Xh (https://econ-gov.inter.trade/assets/index.b8b4803d.js:49:21720)
  at dj (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:3503)
  at Wk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:49590)
  at Vk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:43907)
  at Uk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:43836)
  at Jk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:43681)
  at Ok (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:39643)
  at Hk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:38470)
  at Un (https://econ-gov.inter.trade/assets/index.b8b4803d.js:36:1729)
  at MessagePort.Sn (https://econ-gov.inter.trade/assets/index.b8b4803d.js:36:2141)

Zn @ index.b8b4803d.js:17
Hn @ index.b8b4803d.js:15
error @ index.b8b4803d.js:17
Mi @ index.b8b4803d.js:51
Oi.nn.callback @ index.b8b4803d.js:51
ih @ index.b8b4803d.js:49
lk @ index.b8b4803d.js:51
jk @ index.b8b4803d.js:51
ik @ index.b8b4803d.js:51
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:17 (TypeError#2)
error @ index.b8b4803d.js:17
(anonymous) @ index.b8b4803d.js:17
error (async)
tameConsole @ index.b8b4803d.js:17
repairIntrinsics @ index.b8b4803d.js:20
lockdown$1 @ index.b8b4803d.js:20
(anonymous) @ index.b8b4803d.js:20
index.b8b4803d.js:17 got watchOffers err (Error#3)
error @ index.b8b4803d.js:17
(anonymous) @ index.b8b4803d.js:147
Promise.catch (async)
(anonymous) @ index.b8b4803d.js:147
Rj @ index.b8b4803d.js:51
Ik @ index.b8b4803d.js:51
Fk @ index.b8b4803d.js:51
jg @ index.b8b4803d.js:49
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:15 Error#3: "undefined.0" connection closed
Zn @ index.b8b4803d.js:15
Hn @ index.b8b4803d.js:15
error @ index.b8b4803d.js:17
(anonymous) @ index.b8b4803d.js:147
Promise.catch (async)
(anonymous) @ index.b8b4803d.js:147
Rj @ index.b8b4803d.js:51
Ik @ index.b8b4803d.js:51
Fk @ index.b8b4803d.js:51
jg @ index.b8b4803d.js:49
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:17   at Hn (https://econ-gov.inter.trade/assets/index.b8b4803d.js:84:73278)
  at CTP_DISCONNECT (https://econ-gov.inter.trade/assets/index.b8b4803d.js:84:77337)
  at pn (https://econ-gov.inter.trade/assets/index.b8b4803d.js:84:77677)
  at Object.abort (https://econ-gov.inter.trade/assets/index.b8b4803d.js:84:77768)
  at s$7.disconnectedCallback (https://econ-gov.inter.trade/assets/index.b8b4803d.js:106:2702)
  at ak (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:28746)
  at Zj (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:28422)
  at ak (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:29265)
  at Zj (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:28422)
  at ak (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:29618)
  at Zj (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:28422)
  at ak (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:29618)
  at dk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:30203)
  at ek (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:31814)
  at Xk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:45105)
  at Qk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:44443)
  at Hk (https://econ-gov.inter.trade/assets/index.b8b4803d.js:51:38821)
  at Un (https://econ-gov.inter.trade/assets/index.b8b4803d.js:36:1729)
  at MessagePort.Sn (https://econ-gov.inter.trade/assets/index.b8b4803d.js:36:2141)

Zn @ index.b8b4803d.js:17
Hn @ index.b8b4803d.js:15
error @ index.b8b4803d.js:17
(anonymous) @ index.b8b4803d.js:147
Promise.catch (async)
(anonymous) @ index.b8b4803d.js:147
Rj @ index.b8b4803d.js:51
Ik @ index.b8b4803d.js:51
Fk @ index.b8b4803d.js:51
jg @ index.b8b4803d.js:49
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
index.b8b4803d.js:17 got watchPurses err (Error#3)
error @ index.b8b4803d.js:17
(anonymous) @ index.b8b4803d.js:147
Promise.catch (async)
(anonymous) @ index.b8b4803d.js:147
Rj @ index.b8b4803d.js:51
Ik @ index.b8b4803d.js:51
Fk @ index.b8b4803d.js:51
jg @ index.b8b4803d.js:49
Xk @ index.b8b4803d.js:51
Qk @ index.b8b4803d.js:51
Hk @ index.b8b4803d.js:51
Un @ index.b8b4803d.js:36
Sn @ index.b8b4803d.js:36
```

</details>

**Comment by turadg** [comment]
Fixed by https://github.com/Agoric/dapp-econ-gov/commit/dd653555561b7d97ade85d33535cc8b0521716ea
