### ISSUE TITLE
get latest RPC data in a single HTTP request

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6384]
## What is the Problem Being Solved?

follower-cosmjs `getLatestIterable` makes a request for `currentBlockHeight` and then if it’s higher than the last one we have data for, makes a request for the new data at that height. A consequence is that the latter may hit a different RPC node that doesn’t have that data yet and there’s a retry.

Often this is caught but sometimes it results in:
```
SES_UNHANDLED_REJECTION: (Error#7)\nError#7: Query failed with (26): given height 12289 is greater than latest height 12288: invalid height”. We shouldn’t have any unhandled, even if we stop the height mismatch problem.
Something in Stargate?
Error#1: Query failed with (26): given height 12298 is greater than latest height 12297: invalid height
  at QueryClient.queryRawProof (/home/ari/agoric-sdk/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:75:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async QueryClient.queryVerified (/home/ari/agoric-sdk/node_modules/@cosmjs/stargate/build/queryclient/queryclient.js:39:42)
```

## Description of the Design

Make it so request for data goes to the same endpoint that handled the height query. We thought we could do this by making the endpoint sticky for the function that makes both those calls, but the endpoint is often a pool of validators that are eventually consistent.

We might be able to use HTTP persistent connections to keep getting data from the same host, but that puts a lot of dependence on the pathway and would reduce the load balancing efficiency.

Ideally we'd be able to make a single request for "latest data above this height".  @kriskowal 's https://github.com/cosmos/cosmjs/pull/1278 would provide that capability on the endpoint.

There may be other options yield by 
[ADR 075: RPC Event Subscription Interface](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md) being worked on in [https://github.com/tendermint/tendermint](https://github.com/tendermint/tendermint/issues/7157).

## Security Considerations
--
## Test Plan

--

**Comment by turadg** [comment]
Simplify with https://github.com/Agoric/agoric-sdk/issues/6647
