### ISSUE TITLE
fsync between cosmos and Swingset must be compatible

### ISSUE THREAD

**Issue by shivlim** [Agoric/Agoric#6736]
Agoric Process crashed after unexpected system reboot with the following error.

`BeginBlock error: Error: Unimplemented reset state from 7965906 to 7965903
portHandler threw (Error#1)
panic: Error: Unimplemented reset state from 7965906 to 7965903
goroutine 9 [running]:
github.com/Agoric/agoric-sdk/golang/cosmos/x/swingset.EndBlock({{0x7fe53f1fade0, 0xc000134030}, {0x7fe53f207480, 0xc00ad333c0}, {{0xb, 0x0}, {0xc00ac2dee8, 0x8}, 0x798ccf, {0x614c88f, ...}, ...}, ...}, ...)
	/root/agoric-sdk/golang/cosmos/x/swingset/abci.go:87 +0x375
github.com/Agoric/agoric-sdk/golang/cosmos/x/swingset.AppModule.EndBlock({{}, {{0x7fe53f1e7d60, 0xc001f66340}, {0x7fe53f2088f0, 0xc0001187e0}, {{0x7fe53f205bc8, 0xc0001187e0}, 0xc0000ba000, {0x7fe53f1e7d60, 0xc001f662b0}, ...}, ...}}, ...)
	/root/agoric-sdk/golang/cosmos/x/swingset/module.go:130 +0x7d
github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x7fe53f1fade0, 0xc000134030}, {0x7fe53f207480, 0xc00ad333c0}, {{0xb, 0x0}, {0xc00ac2dee8, 0x8}, 0x798ccf, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/types/module/module.go:499 +0x5bd
github.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).EndBlocker(_, {{0x7fe53f1fade0, 0xc000134030}, {0x7fe53f207480, 0xc00ad333c0}, {{0xb, 0x0}, {0xc00ac2dee8, 0x8}, 0x798ccf, ...}, ...}, ...)
	/root/agoric-sdk/golang/cosmos/app/app.go:854 +0x98
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc0004ff6c0, {0x20?})
	/root/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/baseapp/abci.go:213 +0x2be
github.com/tendermint/tendermint/abci/client.(*committingClient).EndBlockSync(0xc000f7f500, {0xc000f7f500?})
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/abci/client/committing_client.go:339 +0xe8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00ad1bec0?, {0x20?})
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/proxy/app_conn.go:89 +0x24
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x7fe53f1fbc50?, 0xc0135a8180}, {0x7fe53f200e10, 0xc0092c9530}, 0xc001052b40, {0x7fe53f206808, 0xc0092c90a0}, 0xc0011d0ea0?)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/state/execution.go:327 +0x54e
github.com/tendermint/tendermint/state.ExecCommitBlock({0x7fe53f200e10, 0xc0092c9530}, 0xc001052b40, {0x7fe53f1fbc50, 0xc0135a8180}, {0x7fe53f206808?, 0xc0092c90a0?}, 0x106aa070f40e3585?)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/state/execution.go:537 +0x67
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x0}, {0xc0092c7420, 0x8}}, {0xc0092c7428, 0x8}, 0x204855, 0x798cd2, {{0xc00818fc20, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/replay.go:471 +0x248
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0092c7420, 0x8}}, {0xc0092c7428, 0x8}, 0x204855, 0x798cd2, {{0xc00818fc20, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001f75fa0, {0x7fe53f207c60, 0xc0022b9c70})
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0092c7420, 0x8}}, {0xc0092c7428, 0x8}, 0x204855, 0x798cd2, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0004a3b80, {0x7fe53f1f7d08, 0xc007278000}, 0xc00108a9d0, {0x7fe53f1e3408, 0xc0072760d8}, 0x0?, 0x0?, 0xc00108ac50, {0x7fe53f1fbc50, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x7fe53f20c000, 0xc000db31a0}, {0x0, 0x0}, {0x7fe53f1fece0, 0xc0001187e0}, ...}, ...)
	/root/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/server/start.go:272 +0x87d
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0005dcc80?, {0xc000db20f0?, 0x0?, 0x3?})
	/root/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0005dcc80, {0xc0005acdc0, 0x3, 0x4})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00049a000)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000510450?, {0xc000058588, 0x16})
	/root/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/server/cmd/execute.go:36 +0x1eb`

**Comment by mhofman** [comment]
The current hypothesis is that cosmos does not flush / fsync / msync its DBs when commiting a block, whereas Swingset does force a disk flush after commiting a block. Cosmos is really concerned about protection against double sign, so it will flush after these operations, but for other progress, it relies on sync up in case it forgets recently executed blocks.

We have a few different approaches possible:
- Figure out how to get cosmos to flush all the relevant DBs when commiting a block
- Keep multiple blocks worth of chain sends in the host section of the swingStore to deal with the extended cosmos hangover. The question is how many blocks should be remembered / when can older chain sends be dropped. We can either:
  - hard code a number of blocks over which we're more confident the cosmos state will have been flushed
  - figure out if flushes in cosmos can be detected and inform the JS side to drop the corresponding saved chain sends

**Comment by mhofman** [comment]
We decided that the best approach would be to force fsync of cosmos DBs after commit, which would ensure that the existing Cosmos hangover inconsistency logic will be sufficient.

**Comment by mhofman** [comment]
Another validator experience this issue recently:

```
portHandler threw (Error#1)
Error#1: Unimplemented reset state from 9399795 to 9399794

  at blockNeedsExecution (packages/cosmic-swingset/src/launch-chain.js:629:17)
  at blockingSend (packages/cosmic-swingset/src/launch-chain.js:721:13)
  at toSwingSet (packages/cosmic-swingset/src/chain-main.js:469:12)
  at portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:159:22)
  at Object.fromGo (packages/cosmic-swingset/src/chain-main.js:176:31)

BeginBlock error: Error: Unimplemented reset state from 9399795 to 9399794
portHandler threw (Error#1)
panic: Error: Unimplemented reset state from 9399795 to 9399794
```

**Comment by mhofman** [comment]
We got another report of this issue, this time with Polkachu, with a little more logs available:

```
Nov 06 05:18:15 agoric agd[26205]: 2023-11-06T13:18:15.472Z block-manager: block 12374852 commit
Nov 06 05:18:15 agoric agd[26205]: 5:18AM INF commit synced commit=436F6D6D697449447B5B31383920353020323138203130312038312031353720323137203135302031393420323135203133312032353120313132203420313931203139203739203231312038382032353420323233203133382034392037203230372031333620333420393320313236203337203334203233315D3A4243443334347D
Nov 06 05:18:15 agoric agd[26205]: 5:18AM INF committed state app_hash=BD32DA65519DD996C2D783FB7004BF134FD358FEDF8A3107CF88225D7E2522E7 height=12374852 module=state num_txs=0
Nov 06 05:18:15 agoric agd[26205]: 5:18AM INF indexed block exents height=12374852 module=txindex
-- Boot cf41ec8e78044d408ad373040e3442e7 --
Nov 06 05:20:19 agoric systemd[1]: Started cosmovisor.
Nov 06 05:20:20 agoric agd[1251]: 5:20AM INF agd delegating to JS executable args=["ag-chain-cosmos","--home","/home/ubuntu/.agoric","start"] binary=/home/ubuntu/agoric-sdk/packages/cosmic-swingset/src/entrypoint.js
Nov 06 05:20:21 agoric agd[1251]: Removing intrinsics.Symbol.dispose
Nov 06 05:20:21 agoric agd[1251]: Removing intrinsics.Symbol.asyncDispose
Nov 06 05:20:21 agoric agd[1251]: 5:20AM INF starting node with ABCI Tendermint in-process
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start impl=multiAppConn module=proxy msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start connection=query impl=committingClient module=abci-client msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start connection=snapshot impl=committingClient module=abci-client msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start connection=mempool impl=committingClient module=abci-client msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start connection=consensus impl=committingClient module=abci-client msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start impl=EventBus module=events msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start impl=PubSub module=pubsub msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF service start impl=IndexerService module=txindex msg={}
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF ABCI Handshake App Info hash="S$�8�E��R*�*=�5�c�ܦ\x04Jj��grv�?��" height=12374849 module=consensus protocol-version=0 software-version=0.35.0-u11.0
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF ABCI Replay Blocks appHeight=12374849 module=consensus stateHeight=12374853 storeHeight=12374853
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF Applying block height=12374850 module=consensus
Nov 06 05:20:22 agoric agd[1251]: 5:20AM INF minted coins from module account amount=8362938ubld from=mint module=x/bank
Nov 06 05:20:22 agoric agd[1251]: Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js
Nov 06 05:20:22 agoric agd[1251]: 2023-11-06T13:20:22.923Z launch-chain: Launching SwingSet kernel
Nov 06 05:20:29 agoric agd[1251]: 2023-11-06T13:20:29.098Z SwingSet: xsnap: v15: UnhandledPromiseRejectionWarning: No quorum
Nov 06 05:20:29 agoric agd[1251]: 2023-11-06T13:20:29.259Z SwingSet: xsnap: v15: UnhandledPromiseRejectionWarning: No quorum
Nov 06 05:20:29 agoric agd[1251]: 2023-11-06T13:20:29.362Z SwingSet: xsnap: v15: UnhandledPromiseRejectionWarning: No quorum
Nov 06 05:20:29 agoric agd[1251]: 2023-11-06T13:20:29.377Z SwingSet: xsnap: v15: UnhandledPromiseRejectionWarning: No quorum
Nov 06 05:20:33 agoric agd[1251]: 2023-11-06T13:20:33.401Z block-manager: block 12374850 begin
Nov 06 05:20:33 agoric agd[1251]: portHandler threw (Error#1)
Nov 06 05:20:33 agoric agd[1251]: Error#1: Unimplemented reset state from 12374853 to 12374850
```

This shows that the system experienced a crash after committing block 12374853. However because cosmos does not fsync when committing the app DB, the cosmos state got reset to block 12374849 after restart, whereas the tendermint and swingset state was at 12374853 (see `appHeight` vs `stateHeight` & `storeHeight`)

**Comment by mhofman** [comment]
I think I found what needs to change to force cosmos to fsync on Commit!

- `cosmos/iavl` decides whether to fsync when commiting based on a `Sync` option: https://github.com/cosmos/iavl/blob/ddbee0288a3e4a7a7c4a1690aa56876c8a4c0d7b/nodedb.go#L881-L885
- That `Sync` option is provided at construction: 
  - https://github.com/cosmos/iavl/blob/v0.19.5/nodedb.go#L85-L107
  - https://github.com/cosmos/iavl/blob/v0.19.5/mutable_tree.go#L49-L51
- However `cosmos-sdk` does not seem to set that option: https://github.com/agoric-labs/cosmos-sdk/blob/v0.45.11-alpha.agoric.4/store/iavl/store.go#L53-L54

I think if we patch `cosmos-sdk` to set the option, we should no longer experience any failure to restart after system crash. Of course we'd need to test the performance implications of this patch.

**Comment by mhofman** [comment]
Another place (and maybe the only needed) might be to change [`flushMetadata`](https://github.com/agoric-labs/cosmos-sdk/blob/v0.45.11-alpha.agoric.4/store/rootmulti/store.go#L1075), [called from `RootStore.Commit`](https://github.com/agoric-labs/cosmos-sdk/blob/fe7b57811359bbee303152353d14f9b2e2b7ddcf/store/rootmulti/store.go#L432) to use `batch.WriteSync()` instead of `Write`.

**Comment by mhofman** [comment]
Pouring a little cold water on the findings above:
- GoLevelDB only supports sync operations (batch or individual sets).
- Operations are mostly independent, and can end up in different journal files
- There is [no notion of sync barrier in GoLevelDB](https://github.com/syndtr/goleveldb/issues/311), which means flushing the metadata sync above does not guarantee that other writes were flushed. A hard shutdown at that point would be even worse since the chances of DB corruption would be even higher (block metadata not matching block data).
- If the original Google implementation is any reference, the performance of batched [sync writes is likely way too low](https://github.com/google/leveldb#write-performance) to be acceptable.

Somewhere[^1] I read a comment not very promising:
> by design, LevelDB does not and will never support a hard shutdown

[^1]: `https://github.com/pkt-cash/pktd/pull/123`

**Comment by mhofman** [comment]
Today we discussed potential approaches:
- sync the commit metadata batch in cosmos-sdk `Commit`
- issue a `sync` syscall to flush all filesystem caches
- make cosmic-swingset / swing-store more resilient to multiple blocks hangover
- figure out if / why this may be affecting other cosmos chains, and what direction the ecosystem is moving towards for it DB

Since the IVAL implementation is likely to change significantly in newer cosmos-sdk versions, and that syncing the metadata batch write is likely to result in less overall corrupted state for our particular chain use case, the short term approach is to add sync of metadata as a configurable option, enabled by default.

**Comment by aj-agoric** [comment]
I am moving this item from Upgrade 14 to upgrade 15 since it seems we will not plan to have this code complete by departure date of 1/12/24.  c

**Comment by mhofman** [comment]
I have confirmed with an experiment on a follower that has spurious hard reboots and consistently experienced this issue that changing  `flushMetadata` to use `WriteSync` was sufficient for the state after reboot to be consistent.

```
Jan 09 04:37:27 agoric agd[1284]: 4:37AM INF committed state app_hash=338EB07D2917B4CDF464731F9C96A1DE82B5DCD9452D21B8B1232194434493E1 height=13291458 module=state num_txs=0
Jan 09 04:37:27 agoric agd[1284]: 4:37AM INF indexed block exents height=13291458 module=txindex
-- Boot 99925d3877a142f1917c8f62a7b90bdc --
Jan 09 04:39:29 agoric systemd[1]: Started cosmovisor.
Jan 09 04:39:30 agoric agd[1256]: 4:39AM INF agd delegating to JS executable args=["ag-chain-cosmos","--home","/home/ubuntu/.agoric","start"] binary=/home/ubuntu/agoric-sdk/packages/cosmic-swingset/src/entrypoint.js
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF starting node with ABCI Tendermint in-process
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start impl=multiAppConn module=proxy msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start connection=query impl=committingClient module=abci-client msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start connection=snapshot impl=committingClient module=abci-client msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start connection=mempool impl=committingClient module=abci-client msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start connection=consensus impl=committingClient module=abci-client msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start impl=EventBus module=events msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start impl=PubSub module=pubsub msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF service start impl=IndexerService module=txindex msg={}
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF ABCI Handshake App Info hash="����������䬺�*5\x0f\x17�2H$v����h�\x1d" height=13291459 module=consensus protocol-version=0 software-version=0.35.0-u13.0
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF ABCI Replay Blocks appHeight=13291459 module=consensus stateHeight=13291459 storeHeight=13291459
Jan 09 04:39:32 agoric agd[1256]: 4:39AM INF Completed ABCI Handshake - CometBFT and App are synced appHash="����������䬺�*5\x0f\x17�2H$v����h�\x1d" appHeight=13291459 module=consensus
```

**Comment by mhofman** [comment]
SimplyStaking seem to have hit this issue, but surprisingly they only seem to have restarted the service.

```
Apr 15 19:32:15 agoric-mainnet-sentry-mt.mars.lan agd[1126054]: Error#1: Unimplemented reset state from 13952935 to 13952933
Apr 15 19:32:15 agoric-mainnet-sentry-mt.mars.lan agd[1126054]:   at blockNeedsExecution (packages/cosmic-swingset/src/launch-chain.js:748:17)
Apr 15 19:32:15 agoric-mainnet-sentry-mt.mars.lan agd[1126054]:   at doBlockingSend (packages/cosmic-swingset/src/launch-chain.js:882:14)
```

I am not aware of any condition under which we would be able to commit a block on the SwingSet side with **2** uncommitted blocks on the cosmos side.

Some more information from SimplyStaking: they tried to apply a patch, which required checking out a difference commit and rebuilding. Their rebuild failed, so after some delay we suggested `git clean -xfd`, which allowed to rebuild. After the rebuild succeeded, they restarted the agd systemd service. While the rebuild was failing, the node stayed running using previously compiled items (for about 2 days). While we don't support such a scenario (run agd with checkout of other code), it should not have has an impact on commit state.

**Comment by warner** [comment]
Strangelove hit this with an OS crash, in #9680, with a delta of 3 blocks.
