### ISSUE TITLE
consensus failure 31-jan-2023 on some follower nodes

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#6907]
My pismoA follower node halted when receiving block 8480179, at 2023-01-31T05:29:40Z (about 9:30pm pacific time, monday night, Jan 30th). It complained that the 2/3rds-prevoted block had the wrong LastResultsHash, and then stopped with `CONSENSUS_FAILURE`.

```
2023-01-31T05:29:36.153Z block-manager: block 8480178 commit
9:29PM INF commit synced commit=436F6D6D697449447B5B313432203133372037302031363520323232203135382039312031303820313434203134312031313920323132203234312031313320313634203436203131362037382032343220343120323720323433203138382032372031353420313320313534203831203232392031313920323136203132385D3A3831363542327D
9:29PM INF committed state app_hash=8E8946A5DE9E5B6C908D77D4F171A42E744EF2291BF3BC1B9A0D9A51E577D880 height=8480178 module=state num_txs=6
9:29PM INF indexed block height=8480178 module=txindex
9:29PM INF Timed out dur=4819.580104 height=8480179 module=consensus round=0 step=1
9:29PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"BD777AE42C05F3E1AFCD1F6C9F9318BCAAA432474D55159B4C9DA06242651A18","parts":{"hash":"AAF98CA39FFF0B59BC256C53D2EFDFC01C9CEAD00E57B48EEB74106593C79DD6","total":1}},"height":8480179,"pol_round":-1,"round":0,"signature":"dtu3dBLKQV4xhboEoNiBsVjoThTqrWgypPXwUDpHjt4sErcPdOMJs7ahqyB9lj4+T3zgKr3oGJcLIZLz20kFCQ==","timestamp":"2023-01-31T05:29:40.901246403Z"}
9:29PM INF received complete proposal block hash=BD777AE42C05F3E1AFCD1F6C9F9318BCAAA432474D55159B4C9DA06242651A18 height=8480179 module=consensus
9:29PM ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.LastResultsHash.  Expected 0424D589FDBD1FEAB0544F1AA1A9E8B8B0B775A41833222E7D690FB81D7FDCF8, got D39695409FE5ACE9A0B9496FB6B186A5EEE8889F03FDA379B0073F41D792392A" height=8480179 module=consensus round=0
9:29PM ERR CONSENSUS FAILURE!!! err="precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.LastResultsHash.  Expected 0424D589FDBD1FEAB0544F1AA1A9E8B8B0B775A41833222E7D690FB81D7FDCF8, got D39695409FE5ACE9A0B9496FB6B186A5EEE8889F03FDA379B0073F41D792392A" module=consensus stack="goroutine 2267849 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:727 +0x4c\npanic({0x7fe7caef2140, 0xc02864a8e0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc003b2ae00, 0x8165b3, 0x0)\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1408 +0x1679\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc003b2ae00, 0x1c0bdb37f40, {0x1c0b8295a40, 0x28})\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:2123 +0x13ef\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc003b2ae00, 0x1c0bdb37f40, {0x1c0b8295a40?, 0x1c00207c200?})\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc003b2ae00, {{0x7fe7cb1c0bc0?, 0xc0122fd730?}, {0x1c0b8295a40?, 0x0?}})\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:856 +0x170\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc003b2ae00, 0x0)\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:763 +0x3f9\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/home/warner/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:379 +0x12d\n"
```

@arirubinstein  said that our archive node hit the same problem.

**Comment by mhofman** [comment]
I have a follower node that didn't hit the consensus issue. I compared the slog for that last block, and no notable difference exist. In particular all syscalls and activityhash are the same.

Suspecting a cosmos level divergence, not a swingset one.

**Comment by arirubinstein** [comment]
```
precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.LastResultsHash.  Expected 0424D589FDBD1FEAB0544F1AA1A9E8B8B0B775A41833222E7D690FB81D7FDCF8, got D39695409FE5ACE9A0B9496FB6B186A5EEE8889F03FDA379B0073F41D792392A
```
app_hash
```
8E8946A5DE9E5B6C908D77D4F171A42E744EF2291BF3BC1B9A0D9A51E577D880
```

**Comment by joeabbey** [comment]
Any thing unique about your nodes @warner, @mhofman, @arirubinstein?

**Comment by ivanlei** [comment]
This is not being investigated further.
