### ISSUE TITLE
slog sender error: spanKey not found

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6991]
## Describe the bug

I get this weird error in my node log.

## To Reproduce
_IOU_

## Expected behavior
...

## Platform Environment
 - what OS are you using? what version of Node.js?

linux
v16.19.0

 - is there anything special/unusual about your platform?

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

6673db
20230209023556-6673db-linux_amd64

## Additional context
[Add any other context about the problem here.](https://github.com/Agoric/agoric-sdk/pull/6960)

## Screenshots

```
WARNING: slog sender error (Error#4056)
Error tracing slog: {
  type: 'deliver-result',
  crankNum: 901n,
  vatID: 'v2',
  deliveryNum: 33n,
  replay: false,
  dr: [
    'ok',
    null,
    {
      meterType: 'xs-meter-20',
      currentHeapCount: 89254,
      compute: 165310,
      allocate: 42074144,
      timestamps: [Array]
    }
  ],
  time: 1676309901.233356,
  monotime: 497.07128099900007
} (Error#4057)
Error#4057: spanKey not found: ["crank",901]

  at assertKeyExists (packages/store/src/legacy/legacyMap.js:39:23)
  at Object.get (packages/store/src/legacy/legacyMap.js:52:7)
  at Object.get (packages/telemetry/src/slog-to-otel.js:304:26)
  at slogSender (packages/telemetry/src/slog-to-otel.js:586:15)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:924:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:156:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:99:13)
  at process.emit (node:events:513:28)

WARNING: slog sender error (Error#4057)
```

cc @mhofman

**Comment by mhofman** [comment]
I think I know what this one is, and likely fixed in some of the telemetry rework I have on ice. Safe to ignore anyway, our telemetry right now could use some love.
