### ISSUE TITLE
`agoric-upgrade-9` agd is unable to start a chain with `agoric start`

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7051]
`agoric-upgrade-9` agd is unable to start a chain with `agoric start`

```
% agd start                                                                                                                                                     134 ↵ ✭
12:45PM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
12:45PM INF Start chain delegating to JS executable args=["ag-chain-cosmos","--home","/Users/arubinstein/.agoric","start"]
12:45PM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
12:45PM INF starting node with ABCI Tendermint in-process
12:45PM INF service start impl=multiAppConn module=proxy msg={}
12:45PM INF service start connection=query impl=committingClient module=abci-client msg={}
12:45PM INF service start connection=snapshot impl=committingClient module=abci-client msg={}
12:45PM INF service start connection=mempool impl=committingClient module=abci-client msg={}
12:45PM INF service start connection=consensus impl=committingClient module=abci-client msg={}
12:45PM INF service start impl=EventBus module=events msg={}
12:45PM INF service start impl=PubSub module=pubsub msg={}
12:45PM INF service start impl=IndexerService module=txindex msg={}
12:45PM INF ABCI Handshake App Info hash="��\x19\x1e\x1c\x19GbM�\\�M����R\x1d\bK��ڬ\x0f���k\x13\x00" height=111377 module=consensus protocol-version=0 software-version=0.33.0
12:45PM INF ABCI Replay Blocks appHeight=111377 module=consensus stateHeight=111377 storeHeight=111378
12:45PM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x114bc80fc]

goroutine 25 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{_, _}, _, {_, _}, {_, _}, _, {_, _}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/x/upgrade/abci.go:38 +0xb4c
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x115d41040, 0x14000056108}, {0x115d4ffc0, 0x14002099c80}, {{0xb, 0x0}, {0x14001252ab0, 0x11}, 0x1b312, ...}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/types/module/module.go:491 +0x2e8
github.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).BeginBlocker(_, {{0x115d41040, 0x14000056108}, {0x115d4ffc0, 0x14002099c80}, {{0xb, 0x0}, {0x14001252ab0, 0x11}, 0x1b312, ...}, ...}, ...)
	/Users/arubinstein/code/agoric/agoric-sdk/golang/cosmos/app/app.go:817 +0x60
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0x14006666460, 0x20, 0x20}, {{0xb, 0x0}, {0x14001252ab0, 0x11}, 0x1b312, {0x50eca0, ...}, ...}, ...})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/baseapp/abci.go:177 +0x6d4
github.com/tendermint/tendermint/abci/client.(*committingClient).BeginBlockSync(_, {{0x14006666460, 0x20, 0x20}, {{0xb, 0x0}, {0x14001252ab0, 0x11}, 0x1b312, {0x50eca0, ...}, ...}, ...})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/abci/client/committing_client.go:332 +0x184
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0x14006666460, 0x20, 0x20}, {{0xb, 0x0}, {0x14001252ab0, 0x11}, 0x1b312, {0x50eca0, ...}, ...}, ...})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/proxy/app_conn.go:81 +0x4c
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x115d41ee8?, 0x14000170720}, {0x115d487c0, 0x14000d2bbf0}, 0x140001c0d20, {0x115d4f5b8, 0x14001538600}, 0x1b311?)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/state/execution.go:307 +0x2c0
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x14003a48e30, 0x8}}, {0x14001252150, 0x11}, 0x1, 0x1b311, {{0x1400367c660, ...}, ...}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/state/execution.go:140 +0xe4
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0x14003a48e30, 0x8}}, {0x14001252150, 0x11}, 0x1, 0x1b311, {{0x1400367c660, ...}, ...}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/consensus/replay.go:503 +0x180
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x14003a48e30, 0x8}}, {0x14001252150, 0x11}, 0x1, 0x1b311, {{0x1400367c660, ...}, ...}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/consensus/replay.go:416 +0x5c8
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x14000d4bd00, {0x115d50990, 0x140004f6a90})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/consensus/replay.go:268 +0x390
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x14003a48e30, 0x8}}, {0x14001252150, 0x11}, 0x1, 0x1b311, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/node/node.go:329 +0x108
github.com/tendermint/tendermint/node.NewNode(0x14000e343c0, {0x115d3dcf8, 0x14000edd860}, 0x14000d921c0, {0x115d29280, 0x140014f9908}, 0x115d28d40?, 0x14001078680?, 0x14000d92470, {0x115d41ee8, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.23-alpha.agoric.3/node/node.go:777 +0x3cc
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x115d595f0, 0x14000f50c90}, {0x0, 0x0}, {0x115d46198, 0x14000527c30}, ...}, ...)
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/server/start.go:280 +0x698
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0x14000d25b00?, {0x140011b6500?, 0x0?, 0x2?})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/server/start.go:128 +0xd4
github.com/spf13/cobra.(*Command).execute(0x14000d25b00, {0x140011b64e0, 0x2, 0x2})
	/Users/arubinstein/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0x140003e6300)
	/Users/arubinstein/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/arubinstein/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/arubinstein/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14000f46630?, {0x14000e29140, 0x23})
	/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.11-alpha.agoric.1/server/cmd/execute.go:36 +0x1a0
github.com/Agoric/agoric-sdk/golang/cosmos/daemon.RunWithController(0x0?)
	/Users/arubinstein/code/agoric/agoric-sdk/golang/cosmos/daemon/main.go:45 +0x110
main.RunAgCosmosDaemon.func2()
	/Users/arubinstein/code/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:86 +0x94
created by main.RunAgCosmosDaemon
	/Users/arubinstein/code/agoric/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:77 +0x258

```

**Comment by arirubinstein** [comment]
Cannot reproduce in an upgrade scenario:

```
1:08PM INF committed state app_hash=155F7F55F81C5C30AF253998B7AC31F900E6EC1CCC18CBB0D9AE070B13AE2A7C height=62 module=state num_txs=0
1:08PM INF indexed block height=62 module=txindex
1:08PM INF Timed out dur=4965.322 height=63 module=consensus round=0 step=1
1:08PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"37288C6153C5C10438BA422E97106CA52A3D3B56554D224E53EABE7A678C20C1","parts":{"hash":"991A03AE01CFD870D43B88FEF2C35910E42498DC4A390DA6E2CE2544FBF16286","total":1}},"height":63,"pol_round":-1,"round":0,"signature":"biJWzpFf1pHDy1IIz6Km8dEqC34Z0T2ewd7kFiUl6K9aNrl1UG4V2PbmCy7pRbvVaqy1cWR3VYBV0J8wHqCrCw==","timestamp":"2023-02-22T21:08:58.580062Z"}
1:08PM INF received complete proposal block hash=37288C6153C5C10438BA422E97106CA52A3D3B56554D224E53EABE7A678C20C1 height=63 module=consensus
1:08PM INF finalizing commit of block hash=37288C6153C5C10438BA422E97106CA52A3D3B56554D224E53EABE7A678C20C1 height=63 module=consensus num_txs=0 root=155F7F55F81C5C30AF253998B7AC31F900E6EC1CCC18CBB0D9AE070B13AE2A7C
1:08PM ERR UPGRADE "agoric-upgrade-9" NEEDED at height: 63: 
1:08PM ERR CONSENSUS FAILURE!!! err="UPGRADE \"agoric-upgrade-9\" NEEDED at height: 63: " module=consensus stack="goroutine 168 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/Cellar/go/1.19.6/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:727 +0x44\npanic({0x11829cf80, 0x1400103d8d0})\n\t/opt/homebrew/Cellar/go/1.19.6/libexec/src/runtime/panic.go:884 +0x20c\ngithub.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{_, _}, _, {_, _}, {_, _}, _, {_, _}, ...}, ...)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/x/upgrade/abci.go:71 +0xaf8\ngithub.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/x/upgrade/module.go:130\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x11857e180, 0x14000130008}, {0x11858ca60, 0x14003d3e480}, {{0xb, 0x0}, {0x14004016100, 0xc}, 0x3f, ...}, ...}, ...)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/types/module/module.go:479 +0x2d4\ngithub.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).BeginBlocker(_, {{0x11857e180, 0x14000130008}, {0x11858ca60, 0x14003d3e480}, {{0xb, 0x0}, {0x14004016100, 0xc}, 0x3f, ...}, ...}, ...)\n\t/Users/arubinstein/code/agoric/agoric-sdk/golang/cosmos/app/app.go:849 +0x60\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0x140041d85a0, 0x20, 0x20}, {{0xb, 0x0}, {0x14004016100, 0xc}, 0x3f, {0x218ac2f0, ...}, ...}, ...})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.4-alpha.agoric.2/baseapp/abci.go:194 +0x6d4\ngithub.com/tendermint/tendermint/abci/client.(*committingClient).BeginBlockSync(_, {{0x140041d85a0, 0x20, 0x20}, {{0xb, 0x0}, {0x14004016100, 0xc}, 0x3f, {0x218ac2f0, ...}, ...}, ...})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/abci/client/committing_client.go:330 +0x184\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0x140041d85a0, 0x20, 0x20}, {{0xb, 0x0}, {0x14004016100, 0xc}, 0x3f, {0x218ac2f0, ...}, ...}, ...})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/proxy/app_conn.go:81 +0x4c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x11857eff0?, 0x14000d74ea0}, {0x1185856e0, 0x140010208e0}, 0x140049283c0, {0x11858ba60, 0x14000cddc20}, 0x3e?)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/state/execution.go:307 +0x2c0\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x1400107fca0, 0x7}}, {0x1400107fcb0, 0xc}, 0x1, 0x3e, {{0x1400479fa40, ...}, ...}, ...}, ...)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x140004f9180, 0x3f)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1655 +0x800\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x140004f9180, 0x3f)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1564 +0x294\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1499 +0x90\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x140004f9180, 0x3f, 0x0)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1537 +0xa6c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x140004f9180, 0x14003284460, {0x0, 0x0})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:2151 +0x168c\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x140004f9180, 0x14003284460, {0x0?, 0x11672d2d4?})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:1949 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x140004f9180, {{0x118566240?, 0x140005a2b78?}, {0x0?, 0x0?}})\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:856 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x140004f9180, 0x0)\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:783 +0x368\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/Users/arubinstein/go/pkg/mod/github.com/agoric-labs/tendermint@v0.34.19-alpha.agoric.1/consensus/state.go:379 +0xf4\n"

```

```
1:10PM INF Replay last block using real app module=consensus
1:10PM INF applying upgrade "agoric-upgrade-9" at height: 63
1:10PM INF minted coins from module account amount=205stake from=mint module=x/bank
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js
2023-02-22T21:10:59.244Z launch-chain: Launching SwingSet kernel
2023-02-22T21:11:03.156Z launch-chain: Expected SwingSet kernel statistic cosmic_swingset_inbound_queue_length not found
2023-02-22T21:11:03.157Z launch-chain: Expected SwingSet kernel statistic cosmic_swingset_inbound_queue_add not found
2023-02-22T21:11:03.157Z launch-chain: Expected SwingSet kernel statistic cosmic_swingset_inbound_queue_remove not found
2023-02-22T21:11:03.158Z block-manager: block 63 begin
1:11PM INF executed block height=63 module=consensus num_invalid_txs=0 num_valid_txs=0
2023-02-22T21:11:03.169Z block-manager: block 63 commit
1:11PM INF commit synced commit=436F6D6D697449447B5B3139302039332032372035392031323120313933203232312032333320323131203132382033392032342031303820333120353620343120332037203730203230322039342031303320313031203136312031303220313630203730203436203530203634203131312035325D3A33467D
1:11PM INF committed state app_hash=BE5D1B3B79C1DDE9D38027186C1F3829030746CA5E6765A166A0462E32406F34 height=63 module=consensus num_txs=0
1:11PM INF Completed ABCI Handshake - Tendermint and App are synced appHash="\x15_\x7fU�\x1c\\0�%9���1�\x00��\x1c�\x18˰ٮ\a\v\x13�*|" appHeight=62 module=consensus
1:11PM INF Version info block=11 p2p=8 tendermint_version=0.34.23
1:11PM INF This node is a validator addr=4EB8490268E8AAD84BF9B0C653B5697B59B382BA module=consensus pubKey=XRlgl0IpUfcvoPEAz9M7Olu3vqwWO6HRChYUBp76z9o=
1:11PM INF indexed block exents height=63 module=txindex
1:11PM INF P2P Node ID ID=f3ed1118e3e7dc8275cb6714129766e699616f29 file=netstate/config/node_key.json module=p2p
1:11PM INF Adding persistent peers addrs=[] module=p2p
1:11PM INF Adding unconditional peer ids ids=[] module=p2p
1:11PM INF Add our address to book addr={"id":"f3ed1118e3e7dc8275cb6714129766e699616f29","ip":"0.0.0.0","port":26656} book=netstate/config/addrbook.json module=p2p
1:11PM INF service start impl=Node msg={}
1:11PM INF Starting pprof server laddr=localhost:6060
1:11PM INF serve module=rpc-server msg={}
1:11PM INF service start impl="P2P Switch" module=p2p msg={}
1:11PM INF service start impl=BlockchainReactor module=blockchain msg={}
1:11PM INF service start impl=ConsensusReactor module=consensus msg={}
1:11PM INF Reactor  module=consensus waitSync=false
1:11PM INF service start impl=ConsensusState module=consensus msg={}
1:11PM INF service start impl=baseWAL module=consensus msg={} wal=netstate/data/cs.wal/wal
1:11PM INF service start impl=Group module=consensus msg={} wal=netstate/data/cs.wal/wal
1:11PM INF service start impl=TimeoutTicker module=consensus msg={}
1:11PM INF Searching for height height=64 max=0 min=0 module=consensus wal=netstate/data/cs.wal/wal
1:11PM INF Searching for height height=63 max=0 min=0 module=consensus wal=netstate/data/cs.wal/wal
1:11PM INF Found height=63 index=0 module=consensus wal=netstate/data/cs.wal/wal
1:11PM INF Catchup by replaying consensus messages height=64 module=consensus
1:11PM INF Replay: Done module=consensus
1:11PM INF service start impl=Evidence module=evidence msg={}
1:11PM INF service start impl=StateSync module=statesync msg={}
1:11PM INF service start impl=PEX module=pex msg={}
1:11PM INF service start book=netstate/config/addrbook.json impl=AddrBook module=p2p msg={}
1:11PM INF Saving AddrBook to file book=netstate/config/addrbook.json module=p2p size=0
1:11PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
1:11PM INF No addresses to dial. Falling back to seeds module=pex
1:11PM INF Timed out dur=4997.39 height=64 module=consensus round=0 step=1
1:11PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"D382943B9F0A2035BD40C55BF982B3B7DED2405D65F41C5F137E40582D724209","parts":{"hash":"C46194F1E87F4CFCA99725FB251247CD3043625FC41283DCD8C67A470E9404BA","total":1}},"height":64,"pol_round":-1,"round":0,"signature":"VbgqMqY2UUMUT6Epf7XaQdShMp15ULeTxpCj6t/8EOFRAwUqETy1pzrvmAize+ZmPdgLPKc4i/3eGxoDq42IAA==","timestamp":"2023-02-22T21:11:08.250225Z"}
1:11PM INF received complete proposal block hash=D382943B9F0A2035BD40C55BF982B3B7DED2405D65F41C5F137E40582D724209 height=64 module=consensus
1:11PM INF finalizing commit of block hash={} height=64 module=consensus num_txs=0 root=BE5D1B3B79C1DDE9D38027186C1F3829030746CA5E6765A166A0462E32406F34
1:11PM INF minted coins from module account amount=205stake from=mint module=x/bank
2023-02-22T21:11:08.311Z block-manager: block 64 begin
1:11PM INF executed block height=64 module=state num_invalid_txs=0 num_valid_txs=0
2023-02-22T21:11:08.321Z block-manager: block 64 commit
1:11PM INF commit synced commit=436F6D6D697449447B5B393120313932203137312034203632203132302031343020313833203133342032323320313330203139352031333320313530203930203233372032353420323135203833203331203830203138332035203138382032353220313335203235312030203133372031343320323030203133305D3A34307D
1:11PM INF committed state app_hash=5BC0AB043E788CB786DF82C385965AEDFED7531F50B705BCFC87FB00898FC882 height=64 module=state num_txs=0
1:11PM INF indexed block exents height=64 module=txindex
1:11PM INF Timed out dur=4960.548 height=65 module=consensus round=0 step=1
1:11PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"C56F70E2851566AE9A78BB93B81A780B6718F79F19F3AC3F2AB0D63E83B20D7E","parts":{"hash":"43C92FC1A9BA6A6620C434857A9EFAB3B3FA8ABA840E792CBA0E64A5AA2D2D3E","total":1}},"height":65,"pol_round":-1,"round":0,"signature":"mn/tGYfIkbsF/rGyn6n0xE9Hy5RWbQUVBwYpQE0CrJ2V9pICf1XzXEZ/dYchwBitRcp8mjt1jy4CQuk2FkjADA==","timestamp":"2023-02-22T21:11:13.306109Z"}
1:11PM INF received complete proposal block hash=C56F70E2851566AE9A78BB93B81A780B6718F79F19F3AC3F2AB0D63E83B20D7E height=65 module=consensus
1:11PM INF finalizing commit of block hash={} height=65 module=consensus num_txs=0 root=5BC0AB043E788CB786DF82C385965AEDFED7531F50B705BCFC87FB00898FC882

```
