### ISSUE TITLE
Flaky "dispatches to the dead do not harm kernel" CI test failing on anachrophobia

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7078]
We've gotten hit by a flaky test in CI failing on an anachrophobia.

Relevant details from the failing test:
```
anachrophobia strikes vat v2 on delivery 7
delivery completed with 4 expected syscalls remaining
expected: {"0":"vatstoreGet","1":"vom.rc.o-50","length":2}
expected: {"0":"vatstoreGetNextKey","1":"vom.ir.o-50|","length":2}
expected: {"0":"dropImports","1":{"0":"o-50","length":1},"length":2}
expected: {"0":"retireImports","1":{"0":"o-50","length":1},"length":2}
REJECTED from ava test: (Error#124)
Error#124: historical inaccuracy in replay of v2
  at Object.finishReplayDelivery (.../swingset-vat/src/kernel/vat-loader/transcript.js:81:13)
  at replayOneDelivery (.../swingset-vat/src/kernel/vat-loader/manager-helper.js:191:19)
  at async Object.replayTranscript (.../swingset-vat/src/kernel/vat-loader/manager-helper.js:218:1)
  at async ensureVatOnline (.../swingset-vat/src/kernel/vat-warehouse.js:133:1)
  at async Object.start (.../swingset-vat/src/kernel/vat-warehouse.js:181:1)
  at async Object.start (.../swingset-vat/src/kernel/kernel.js:1565:1)
  at async makeSwingsetController (packages/SwingSet/src/controller/controller.js:309:3)
  at async buildVatController (packages/SwingSet/src/controller/controller.js:543:22)
  at async packages/SwingSet/test/vat-admin/terminate/test-terminate.js:414:16

not ok 182 - vat-admin › terminate › terminate › dispatches to the dead do not harm kernel %ava-dur=6911ms
```

I could not reproduce locally, but it happened at least twice in CI:
- https://github.com/Agoric/agoric-sdk/actions/runs/4259336378/jobs/7411503443#step:5:1385
- https://github.com/Agoric/agoric-sdk/actions/runs/4265725846/jobs/7425453636#step:5:1367

May be related to https://github.com/Agoric/agoric-sdk/issues/6784

**Comment by warner** [comment]
Is this running under the local (Node.js) worker? We've had rotten luck getting GC to work consistently under Node, and this might be another expression of that. #5202 / #4936

**Comment by warner** [comment]
I'm starting to think that all but the simplest of GC tests should be configured to run only under XS.

**Comment by mhofman** [comment]
I guess it was both times under Node. We should probably separate more clearly the tests that don't use xsnap-worker. I can't really see a good reason to run tests that use liveslots under node.

**Comment by ivanlei** [comment]
This is a dupe of #6692
