### ISSUE TITLE
Clean local master failing in packages/solo on new Mac

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#7243]
On the new Mac I just got, after a clean build on a clean local copy of agoric-sdk master, a `yarn test` in `packages/solo` fails as follows.

I mention that it is a new Mac in case there's something I need to configure afresh that I don't know about.

```
solo(master)$ yarn test
yarn run v1.22.19
$ ava

# connecting
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
.
.
.
.
.
.
.
.
.
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js

REJECTED from ava test: (Error#1)
Error#1: CapTP fixture exited with null
  at ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)
  at ChildProcess.emit (node:events:513:28)

  ✘ [fail]: setup Rejected promise returned by test
  ✘ [fail]: teardown Rejected promise returned by test
.
SES_UNHANDLED_REJECTION: (Error#2)
Error#2: kill ESRCH
  at process.kill (packages/solo/test/captp-fixture.js:125:13)
  at process.emit (node:events:525:35)

  ✘ 6 tests remaining in test/test-home.js
  ─

  setup

  Rejected promise returned by test. Reason:

  Error {
    message: 'CapTP fixture exited with null',
  }

  › ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)



  teardown

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'teardown is not a function',
  }

  › packages/solo/test/test-home.js:187:9

  ─

  2 hooks failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by michaelfig** [comment]
Try: `NOISY=1 yarn test` to see the error.

**Comment by erights** [comment]
Seems the same

```
solo(master)$ NOISY=1 yarn test
yarn run v1.22.19
$ ava

# connecting
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
.
.
.
.
.
.
.
.
.
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js

REJECTED from ava test: (Error#1)
Error#1: CapTP fixture exited with null
  at ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)
  at ChildProcess.emit (node:events:513:28)

  ✘ [fail]: setup Rejected promise returned by test
  ✘ [fail]: teardown Rejected promise returned by test
.
SES_UNHANDLED_REJECTION: (Error#2)
Error#2: kill ESRCH
  at process.kill (packages/solo/test/captp-fixture.js:125:13)
  at process.emit (node:events:525:35)

  ✘ 6 tests remaining in test/test-home.js
  ─

  setup

  Rejected promise returned by test. Reason:

  Error {
    message: 'CapTP fixture exited with null',
  }

  › ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)



  teardown

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'teardown is not a function',
  }

  › packages/solo/test/test-home.js:187:9

  ─

  2 hooks failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by michaelfig** [comment]
Do you have `make` installed?  I think it comes included with `XCode`.

**Comment by erights** [comment]
It seems I do

```
(2):solo(master)$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by michaelfig** [comment]
Last thing to try, then let's have a vidchat:

```
cd packages/solo/test
sh -x ./startsolo.sh
```

**Comment by erights** [comment]
What does
```
Illegal instruction: 4
```
mean?

```
(1):test(master)$ pwd
/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/solo/test
test(master)$ sh -x ./startsolo.sh
+ set -e
+ PORT=8000
++ cd ..
++ pwd
+ AG_SOLO=/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/solo/bin/ag-solo
+ TDIR=/var/folders/g1/crzbwthn3n72s_8smhth9g_c0000gn/T//startsolo.90657
+ trap 'rm -rf "$TDIR"' EXIT
+ /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/solo/bin/ag-solo init /var/folders/g1/crzbwthn3n72s_8smhth9g_c0000gn/T//startsolo.90657 --egresses=fake --webport=8000 --defaultManagerType=local
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
+ cd /var/folders/g1/crzbwthn3n72s_8smhth9g_c0000gn/T//startsolo.90657
+ /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/solo/bin/ag-solo set-fake-chain --delay=0 mySimGCI
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
+ exec /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/solo/bin/ag-solo start
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js
Illegal instruction: 4
```

**Comment by mhofman** [comment]
Which node version ?

**Comment by erights** [comment]
Good guess! I was using 18.

But after switching to 16 I get exactly the same symptoms.

**Comment by erights** [comment]
NOT exactly the same. Now begins with

```
(1):solo(master)$ yarn test
yarn run v1.22.19
$ ava

# connecting
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
error running ag-solo: (Error#1)
Error#1: The module '/Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
  at makeSwingStore (packages/swing-store/src/swingStore.js:406:12)
  at initSwingStore (packages/swing-store/src/swingStore.js:945:10)
  at resetState (packages/solo/src/reset-state.js:13:29)
  at solo (packages/solo/src/main.js:95:13)
  at packages/solo/src/entrypoint.js:20:1
  at async Promise.all (index 0)
```

I know what to try next!

**Comment by mhofman** [comment]
18 should be supported on master (it's only if you had gone higher that problems may arise)

**Comment by erights** [comment]
Yeah. After rebuilding the world, I'm back to the original symptoms without the additional prelude.

**Comment by michaelfig** [comment]
@erights, any progress on this issue?

**Comment by erights** [comment]
> @erights, any progress on this issue?

I just checked. Apparently not :(

Current symptoms below:

```
solo(master)$ yarn test
yarn run v1.22.19
$ ava

# connecting
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
SES Lockdown using options from environment variables "LOCKDOWN_ERROR_TAMING"
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js

REJECTED from ava test.before("setup"): (Error#1)
Error#1: CapTP fixture exited with null
  at ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)
  at ChildProcess.emit (node:events:513:28)

  ✘ [fail]: setup Rejected promise returned by test
  ✘ [fail]: teardown Rejected promise returned by test
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

  Uncaught exception in test/test-home.js

  Error: kill ESRCH
    at process.kill (packages/solo/test/captp-fixture.js:125:13)
    at process.emit (node:events:513:28)

  › process.kill (packages/solo/test/captp-fixture.js:125:13)

  ✘ Exiting due to process.exit() when running test/test-home.js

  Error: Unexpected process.exit()
    at process.emit (node:events:525:35)

(Error#2)
Error#2: kill ESRCH
  at process.kill (packages/solo/test/captp-fixture.js:125:13)
  at process.emit (node:events:513:28)

  ✘ test/test-home.js exited with a non-zero exit code: -1
  ─

  setup

  Rejected promise returned by test. Reason:

  Error {
    message: 'CapTP fixture exited with null',
  }

  › ChildProcess.<anonymous> (packages/solo/test/captp-fixture.js:110:16)



  teardown

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'teardown is not a function',
  }

  › packages/solo/test/test-home.js:187:9

  ─

  2 hooks failed
  1 uncaught exception
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(1):solo(master)$ 
```

**Comment by michaelfig** [comment]
There was confusion between `amd64` and `arm64` binaries, and MacOS's ability to choose whether it ran native `arm64` binaries or emulated `amd64`.  I'll leave it to somebody else to summarise how to work around these issues.

**Comment by erights** [comment]
Haven't seen or heard about such problems in a long time. Closing.
