### ISSUE TITLE
Error#1: unknown record updated brand when listing wallet

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7699]
4e5ca113512d831026c29a0c9d37703f93fef72b
```
# agoric wallet show --from $GOV1ADDR
agoric: (Error#1)
Error#1: unknown record updated brand

  at Object.update (packages/smart-wallet/src/utils.js:68:15)
  at coalesceWalletState (packages/agoric-cli/src/lib/wallet.js:105:15)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/wallet.js:165:25)
  at async main (packages/agoric-cli/src/main.js:400:5)

root@0601fc45c85e:/usr/src/agoric-sdk# echo $GOV1ADDR
agoric18rl8v6kgf09fq0y3sutsc3alttrjky3nl2mdqy
root@0601fc45c85e:/usr/src/agoric-sdk# 
```

To Reproduce:

```
1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `make local_sdk build` (once)
4. `make run`
5. run `agoric wallet show --from $GOV1ADDR`
```

**Comment by dckc** [comment]
for ref: branch `ari/vaultstest` is currently at a450b1a

**Comment by dckc** [comment]
seems a little familiar... but #7674 / #7656 seems to be a little different

**Comment by samsiegart** [comment]
I think this is fixed between https://github.com/Agoric/agoric-sdk/pull/7704 and https://github.com/Agoric/agoric-sdk/pull/7707 but we can reopen if not
