### ISSUE TITLE
Error#1: Check failed unable to accept ec charter 

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#7701]
4e5ca113512d831026c29a0c9d37703f93fef72b

```
# agops ec charter --send-from $GOV1ADDR 
(Error#1)
Error#1: Check failed

  at findContinuingIds (packages/agoric-cli/src/lib/wallet.js:163:3)
  at toOffer (packages/agoric-cli/src/commands/ec.js:188:25)
  at processOffer (packages/agoric-cli/src/commands/ec.js:81:19)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/ec.js:203:7)
  at async packages/agoric-cli/src/bin-agops.js:76:3

root@7a7f0ec46caf:/usr/src/agoric-sdk# echo $GOV1ADDR
agoric18rl8v6kgf09fq0y3sutsc3alttrjky3nl2mdqy

```

to reproduce:
```
1. `git clone git@github.com:Agoric/agoric-sdk.git && cd agoric-sdk && checkout ari/vaultstest`
2. `cd packages/deployment/upgrade-test`
3. `make local_sdk build` (once)
4. `make run`
5. run `agops ec charter --send-from $GOV1ADDR`
```

**Comment by erights** [comment]
Is this fixed by https://github.com/Agoric/agoric-sdk/pull/7704 ? Please review.
