### ISSUE TITLE
`agops inter auction status` fails to handle missing schedule info

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7786]
## Describe the bug

`agops inter auction status` fails on unexpected input

## To Reproduce

_IOU_

## Expected behavior

If some parts are missing, show the rest.

## Platform Environment

_I was looking at @otoole-brendan 's screen while he was in some version upgrade-testing container_

 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context

liquidation testing

## Screenshots

```
root@be7d8697f9db:/usr/src/agoric-sdk# agops inter bid by-price --price 7.5 --give 75IST --from $GOV1ADDR --keyr^Cg-backend=test
root@be7d8697f9db:/usr/src/agoric-sdk#
root@be7d8697f9db:/usr/src/agoric-sdk# agops inter auction status
(TypeError#1)
TypeError#1: Cannot read properties of null (reading 'absValue')
 at Object.absTime (packages/agoric-cli/src/commands/inter.js:68:44)
 at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:293:32)
 at async packages/agoric-cli/src/bin-agops.js:78:3
root@be7d8697f9db:/usr/src/agoric-sdk#
root@be7d8697f9db:/usr/src/agoric-sdk#
root@be7d8697f9db:/usr/src/agoric-sdk# agops inter auction status
(TypeError#1)
TypeError#1: Cannot read properties of null (reading 'absValue')
 at Object.absTime (packages/agoric-cli/src/commands/inter.js:68:44)
 at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:293:32)
 at async packages/agoric-cli/src/bin-agops.js:78:3
```

**Comment by dckc** [comment]
Looks like a consequence of e893e0e6f1c1a30e6192417903783991eea4584a where some fields of `ScheduleNotification` became optional.

Oddly, that commit is marked as a refactor, but also marked as closing a bug. Here we see that it's a also breaking change of sorts.

**Comment by dckc** [comment]
Here's hoping we can tightly connect the documentation for the types of the data published via RPC along with the snapshots of example data such as [test-auctionContract.js.md](https://github.com/Agoric/agoric-sdk/blob/master/packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md)
