### ISSUE TITLE
Why am I getting "out of date" bundles on a fresh `yarn build` on clean master?

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#8103]
On what I believe is a clean master, when I `yarn build` I get many "out of date:" error such as

```
> @agoric/governance
$ yarn build:bundles
$ node ./scripts/build-bundles.js
bundle-source --to /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/bundles /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/src/contractGovernor.js contractGovernor /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/tools/puppetContractGovernor.js puppetContractGovernor /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/src/committee.js committee /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/src/noActionElectorate.js noActionElectorate /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/governance/src/binaryVoteCounter.js binaryVoteCounter
(Error#1)
Error#1: out of date: [
  {
    relativePath: '../../../../node_modules/@endo/pass-style/src/passStyleOf.js',
    mtime: '2023-07-27T05:37:09.615Z'
  }
] . contractGovernor bundled at 2023-07-27T05:36:13.280Z
  at makeError (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/src/error/assert.js:273:17)
  at fail (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/src/error/assert.js:387:20)
  at Fail (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/ses/src/error/assert.js:396:39)
  at validate (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/@endo/bundle-source/cache.js:251:11)
  at async Object.validateOrAdd (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/@endo/bundle-source/cache.js:271:16)
  at async main (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/@endo/bundle-source/src/main.js:36:5)
```

**Comment by erights** [comment]
When I removed all bundles manually, the problem went away. Is there an existing operation I should have done, like `yarn clean`, to remove all these automatically?

In any case, I'm closing this issue as fixed.

**Comment by kriskowal** [comment]
The bundle cache is keyed on mtime. Switching branches might confuse the
cache.

**Comment by erights** [comment]
Keying on time seems inherently unsafe. What if the machine's clock is corrected back to an earlier time? Why not key on hash?

**Comment by erights** [comment]
But still, assuming the caches are confused, how is one supposed to clear all these out?
