### ISSUE TITLE
Error when trying to check bid list in CLI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#8535]
## Describe the bug
As part of upgrade 12 testing, I noticed while using the CLI that I was unable to run the command to see my bids and received an error I had not previously received from testing in the past.

## To Reproduce
-  [ ] git clone https://github.com/Agoric/agoric-sdk
- [ ] cd agoric-sdk
- [ ] SKIP_DOWNLOAD=false ./bin/agd build
- [ ] export PATH=$PWD/bin:$PATH 
- [ ] alias inter="yarn run --silent agops inter"
- [ ] export AGORIC_NET=emerynet
- [ ]  agd keys add test-acct --keyring-backend=test         
override the existing name test-acct [y/N]: y
- [ ] inter bid list --from test-acct --keyring-backend=test

## Expected behavior
I should be able to see my bids (if any)

## Screenshots

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid list --from test-acct --keyring-backend=test
(Error#1)
Error#1: error code 38 reading data of published.wallet.agoric10r0mrv6dyyq8hnn4ek77sc2yllc6fs9gper8gs: no data for vstorage path: not found

  at packages/agoric-cli/src/lib/rpc.js:82:17
  at async Object.readAt (packages/agoric-cli/src/lib/rpc.js:118:19)
  at async Object.readFully (packages/agoric-cli/src/lib/rpc.js:140:38)
  at async storedWalletState (packages/agoric-cli/src/lib/wallet.js:215:21)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:571:34)

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid list --all --from test-acct --keyring-backend=test
(Error#1)
Error#1: error code 38 reading data of published.wallet.agoric10r0mrv6dyyq8hnn4ek77sc2yllc6fs9gper8gs: no data for vstorage path: not found

  at packages/agoric-cli/src/lib/rpc.js:82:17
  at async Object.readAt (packages/agoric-cli/src/lib/rpc.js:118:19)
  at async Object.readFully (packages/agoric-cli/src/lib/rpc.js:140:38)
  at async storedWalletState (packages/agoric-cli/src/lib/wallet.js:215:21)
  at async Promise.all (index 1)
  at async Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:571:34)

**Comment by mhofman** [comment]
after clone `git switch agoric-upgrade-12-rc0`

**Comment by otoole-brendan** [comment]
Still getting same error after running above ^^ and rebuilding etc.

**Comment by mhofman** [comment]
@otoole-brendan can you double check that `master` from agoric-sdk allows you to check bids?
