### ISSUE TITLE
Node on agoric-emerynet-8 crashes right after start

### ISSUE THREAD

**Issue by fmira21** [Agoric/Agoric#8704]
Hi guys! 

I've just deployed a fresh Agoric node on `agoric-emerynet-8` using your `ghcr.io/agoric/agoric-sdk:39`.
Cannot start it since it crashes with the following error (see below).

Can you advise what I should pay attention to?

Thank you in advance!

```
Removing intrinsics.Symbol.dispose
Removing intrinsics.Symbol.asyncDispose
7:59PM INF starting node with ABCI Tendermint in-process
7:59PM INF service start impl=multiAppConn module=proxy msg={}
7:59PM INF service start connection=query impl=committingClient module=abci-client msg={}
7:59PM INF service start connection=snapshot impl=committingClient module=abci-client msg={}
7:59PM INF service start connection=mempool impl=committingClient module=abci-client msg={}
7:59PM INF service start connection=consensus impl=committingClient module=abci-client msg={}
7:59PM INF service start impl=EventBus module=events msg={}
7:59PM INF service start impl=PubSub module=pubsub msg={}
7:59PM INF service start impl=IndexerService module=txindex msg={}
7:59PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.35.0-u13.0
7:59PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
7:59PM INF created new capability module=ibc name=ports/transfer
7:59PM INF port binded module=x/ibc/port port=transfer
7:59PM INF claimed capability capability=1 module=transfer name=ports/transfer
7:59PM INF created new capability module=ibc name=ports/icahost
7:59PM INF port binded module=x/ibc/port port=icahost
7:59PM INF claimed capability capability=2 module=icahost name=ports/icahost
portHandler threw (Error#1)
Error#1: Cannot find module '/usr/src/agoric-sdk/node_modules/@agoric/vats/decentral-test-psm-config.json' imported from /usr/src/agoric-sdk/packages/cosmic-swingset/src/chain-main.js
  at launchAndInitializeSwingSet (packages/cosmic-swingset/src/chain-main.js:362:27)
  at toSwingSet (packages/cosmic-swingset/src/chain-main.js:674:30)
panic: cannot initialize Controller: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/agoric-sdk/node_modules/@agoric/vats/decentral-test-psm-config.json' imported from /usr/src/agoric-sdk/packages/cosmic-swingset/src/chain-main.js
goroutine 24 [running]:
github.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).initController(_, {{0x7fd4bb15a638, 0xc000126030}, {0x7fd4bb167cb8, 0xc000c04e40}, {{0x0, 0x0}, {0xc0000de108, 0x11}, 0x0, ...}, ...}, ...)
	/usr/src/agoric-sdk/golang/cosmos/app/app.go:928 +0x673
github.com/Agoric/agoric-sdk/golang/cosmos/app.(*GaiaApp).InitChainer(_, {{0x7fd4bb15a638, 0xc000126030}, {0x7fd4bb167cb8, 0xc000c04e40}, {{0x0, 0x0}, {0xc0000de108, 0x11}, 0x0, ...}, ...}, ...)
	/usr/src/agoric-sdk/golang/cosmos/app/app.go:983 +0x389
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000b7b880, {{0x2d4c8f1b, 0xedc12bb11, 0x0}, {0xc0000de108, 0x11}, 0xc000bdcce0, {0x7fd4bbfeee88, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.16-alpha.agoric.3/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*committingClient).InitChainSync(0xc000cabc20, {{0x2d4c8f1b, 0xedc12bb11, 0x0}, {0xc0000de108, 0x11}, 0xc000bdcce0, {0x7fd4bbfeee88, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/abci/client/committing_client.go:316 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000e90090?, {{0x2d4c8f1b, 0xedc12bb11, 0x0}, {0xc0000de108, 0x11}, 0xc000bdcce0, {0x7fd4bbfeee88, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x7fd4ba4cc396, 0x7}}, {0xc0000de108, 0x11}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/consensus/replay.go:319 +0xf18
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001295c40, {0x7fd4bb16ab38, 0xc00011ed00})
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x7fd4ba4cc396, 0x7}}, {0xc0000de108, 0x11}, 0x1, 0x0, ...}, ...)
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0000e52c0, {0x7fd4bb1571a0, 0xc000ab75e0}, 0xc000d07360, {0x7fd4bb1420a0, 0xc00011cf48}, 0x0?, 0x0?, 0xc000d07570, {0x7fd4bb15b438, ...}, ...)
	/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/node/node.go:779 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x7fd4bb174a10, 0xc000cb39b0}, {0xc000c782e8, 0x11}, {0x7fd4bb15f5e0, 0xc0000b8030}, ...}, ...)
	/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.16-alpha.agoric.3/server/start.go:280 +0x93d
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000ea7b00?, {0x7fd4bbfeee88?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.16-alpha.agoric.3/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000ea7b00, {0x7fd4bbfeee88, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ee300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000012bd0?, {0xc000c78450, 0x16})
	/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.45.16-alpha.agoric.3/server/cmd/execute.go:36 +0x1eb
github.com/Agoric/agoric-sdk/golang/cosmos/daemon.RunWithController(0x0?)
	/usr/src/agoric-sdk/golang/cosmos/daemon/main.go:45 +0x10c
main.RunAgCosmosDaemon.func2()
	/usr/src/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:86 +0x87
created by main.RunAgCosmosDaemon
	/usr/src/agoric-sdk/golang/cosmos/cmd/libdaemon/main.go:77 +0x1f6
```

**Comment by mhofman** [comment]
It looks like you are trying to sync up from genesis using the latest software version. Most likely you want to start from state-sync or a community snapshot.

For state-sync you might be able to follow instructions like https://polkachu.com/state_sync/agoric but using https://emerynet.rpc.agoric.net:443 as the RPC server

**Comment by fmira21** [comment]
Hi @mhofman 
Thank you for this, much appreciated!
Just applied the snapshot, node is syncing, closing the issue.
