### ISSUE TITLE
"unexpected return pc" crash in go runtime by a mainnet follower

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#9138]
My mainnet follower `agreeable` crashed while processing block 14,119,309 (on 08-Mar-2024). The headline of the crashdump says `unexpected return pc for runtime.selectgo called from 0x0`. I didn't notice the failure for a few weeks, but I've restarted the node and it's been catching up normally for the last hour, so I don't think there is any fatally-corrupted state. Might be random corruption overwriting the stack somehow?

This is running from tag `agoric-upgrade-13`.

The primary stack trace and goroutine is here. I'll attach the full node output separately.

```
2024-03-08T23:54:11.846Z block-manager: block 14119309 begin
runtime: g 35609: unexpected return pc for runtime.selectgo called from 0x0
stack: frame={sp:0xc022a36d80, fp:0xc022a36ec0} stack=[0xc022a36800,0xc022a37000)
0x000000c022a36c80:  0x3fe0000000000000  0x0000000000000000 
0x000000c022a36c90:  0x41cdcd6500000000  0x0000000000000000 
0x000000c022a36ca0:  0x7546587c029b7007  0xf808ddc307f54f39 
0x000000c022a36cb0:  0x5e427188dcca7608  0x3b5ec49b44bcec5d 
0x000000c022a36cc0:  0x7546587c029b7007  0x000000c0346c4ec0 
0x000000c022a36cd0:  0x000000c0346c4ea0  0x0000000000000000 
0x000000c022a36ce0:  0x00007f95eaee8ca0  0x00007f95ebf07560 
0x000000c022a36cf0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36d00:  0x0000000000000000  0x0000000000000000 
0x000000c022a36d10:  0x000000c022a36d70  0x00007f95e9045e7d <runtime.sigpanic+0x000000000000037d> 
0x000000c022a36d20:  0x00007f95eaee8ca0  0x00007f95ebf07560 
0x000000c022a36d30:  0x0405060700010203  0x0c0d0e0f08090a0b 
0x000000c022a36d40:  0x0000000000000000  0x000000c03ee6ef00 
0x000000c022a36d50:  0x000000c0346c4ea0  0x0000000000000000 
0x000000c022a36d60:  0x0000000000000004  0x000000c0618795c0 
0x000000c022a36d70:  0x000000c022a36eb0  0x00007f95e9041e66 <runtime.selectgo+0x00000000000007c6> 
0x000000c022a36d80: <0x000000c022a36f68  0x0000000000000005 
0x000000c022a36d90:  0x00000a8c46505853  0x0000000000000207 
0x000000c022a36da0:  0x0000000000000a88  0x0000000000000000 
0x000000c022a36db0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36dc0:  0x0000000000000203  0x0000000000000000 
0x000000c022a36dd0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36de0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36df0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e00:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e10:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e20:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e30:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e40:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e50:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e60:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e70:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e80:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e90:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ea0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36eb0:  0x0000000000000000 !0x0000000000000000 
0x000000c022a36ec0: >0x0000000000000000  0x0000000000000000 
0x000000c022a36ed0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ee0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ef0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36f00:  0x0004000300000001  0x0002000100030000 
0x000000c022a36f10:  0x000000c02d32aff0  0x000000c031f340f0 
0x000000c022a36f20:  0x0000000000000002  0x000000c022a36fb8 
0x000000c022a36f30:  0x000000c020e7d400  0x00007f95e8ffc379 <runtime.closechan+0x0000000000000399> 
0x000000c022a36f40:  0x0000000000000000  0x0000000000000000 
0x000000c022a36f50:  0x0000000000d77311  0x000000c00501d620 
0x000000c022a36f60:  0x0000000000000028  0x000000c02d54bce0 
0x000000c022a36f70:  0x0000000000000000  0x000000c037b78480 
0x000000c022a36f80:  0x000000c022a36f40  0x000000c0618795c0 
0x000000c022a36f90:  0x0000000000000000  0x000000c02d54be00 
0x000000c022a36fa0:  0x0000000000000000  0x000000c0218db140 
0x000000c022a36fb0:  0x0000000000000000  0x000000c022a36fd0 
fatal error: unknown caller pc

runtime stack:
runtime.throw({0x7f95ea4d5813?, 0x7f95ebf5b840?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5f fp=0x7f92c908e980 sp=0x7f92c908e950 pc=0x7f95e902ea7f
runtime.gentraceback(0xc0346c4ea0?, 0x7f92c908ed01?, 0x1007f92c908ed08?, 0xc0346c4ea0, 0x0, 0x0, 0x7fffffff, 0x7f92c908ed28, 0x400000002?, 0x0)
	/usr/local/go/src/runtime/traceback.go:270 +0x1bb0 fp=0x7f92c908ecd8 sp=0x7f92c908e980 pc=0x7f95e9056bb0
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:645 +0x6b fp=0x7f92c908ed50 sp=0x7f92c908ecd8 pc=0x7f95e902dc0b
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:496 +0x46 fp=0x7f92c908ed58 sp=0x7f92c908ed50 pc=0x7f95e9063b66

goroutine 35609 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:463 fp=0xc022a36c20 sp=0xc022a36c18 pc=0x7f95e9063b00
runtime.addOneOpenDeferFrame(0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/panic.go:644 +0x69 fp=0xc022a36c60 sp=0xc022a36c20 pc=0x7f95e902db49
panic({0x7f95eaee8ca0, 0x7f95ebf07560})
	/usr/local/go/src/runtime/panic.go:844 +0x113 fp=0xc022a36d20 sp=0xc022a36c60 pc=0x7f95e902e393
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:841 +0x37d fp=0xc022a36d80 sp=0xc022a36d20 pc=0x7f95e9045e7d
runtime: g 35609: unexpected return pc for runtime.selectgo called from 0x0
stack: frame={sp:0xc022a36d80, fp:0xc022a36ec0} stack=[0xc022a36800,0xc022a37000)
0x000000c022a36c80:  0x3fe0000000000000  0x0000000000000000 
0x000000c022a36c90:  0x41cdcd6500000000  0x0000000000000000 
0x000000c022a36ca0:  0x7546587c029b7007  0xf808ddc307f54f39 
0x000000c022a36cb0:  0x5e427188dcca7608  0x3b5ec49b44bcec5d 
0x000000c022a36cc0:  0x7546587c029b7007  0x000000c0346c4ec0 
0x000000c022a36cd0:  0x000000c0346c4ea0  0x0000000000000000 
0x000000c022a36ce0:  0x00007f95eaee8ca0  0x00007f95ebf07560 
0x000000c022a36cf0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36d00:  0x0000000000000000  0x0000000000000000 
0x000000c022a36d10:  0x000000c022a36d70  0x00007f95e9045e7d <runtime.sigpanic+0x000000000000037d> 
0x000000c022a36d20:  0x00007f95eaee8ca0  0x00007f95ebf07560 
0x000000c022a36d30:  0x0405060700010203  0x0c0d0e0f08090a0b 
0x000000c022a36d40:  0x0000000000000000  0x000000c03ee6ef00 
0x000000c022a36d50:  0x000000c0346c4ea0  0x0000000000000000 
0x000000c022a36d60:  0x0000000000000004  0x000000c0618795c0 
0x000000c022a36d70:  0x000000c022a36eb0  0x00007f95e9041e66 <runtime.selectgo+0x00000000000007c6> 
0x000000c022a36d80: <0x000000c022a36f68  0x0000000000000005 
0x000000c022a36d90:  0x00000a8c46505853  0x0000000000000207 
0x000000c022a36da0:  0x0000000000000a88  0x0000000000000000 
0x000000c022a36db0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36dc0:  0x0000000000000203  0x0000000000000000 
0x000000c022a36dd0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36de0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36df0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e00:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e10:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e20:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e30:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e40:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e50:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e60:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e70:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e80:  0x0000000000000000  0x0000000000000000 
0x000000c022a36e90:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ea0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36eb0:  0x0000000000000000 !0x0000000000000000 
0x000000c022a36ec0: >0x0000000000000000  0x0000000000000000 
0x000000c022a36ed0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ee0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36ef0:  0x0000000000000000  0x0000000000000000 
0x000000c022a36f00:  0x0004000300000001  0x0002000100030000 
0x000000c022a36f10:  0x000000c02d32aff0  0x000000c031f340f0 
0x000000c022a36f20:  0x0000000000000002  0x000000c022a36fb8 
0x000000c022a36f30:  0x000000c020e7d400  0x00007f95e8ffc379 <runtime.closechan+0x0000000000000399> 
0x000000c022a36f40:  0x0000000000000000  0x0000000000000000 
0x000000c022a36f50:  0x0000000000d77311  0x000000c00501d620 
0x000000c022a36f60:  0x0000000000000028  0x000000c02d54bce0 
0x000000c022a36f70:  0x0000000000000000  0x000000c037b78480 
0x000000c022a36f80:  0x000000c022a36f40  0x000000c0618795c0 
0x000000c022a36f90:  0x0000000000000000  0x000000c02d54be00 
0x000000c022a36fa0:  0x0000000000000000  0x000000c0218db140 
0x000000c022a36fb0:  0x0000000000000000  0x000000c022a36fd0 
runtime.selectgo(0x0, 0x0, 0x0?, 0x0, 0x0?, 0x0)
	/usr/local/go/src/runtime/select.go:328 +0x7c6 fp=0xc022a36ec0 sp=0xc022a36d80 pc=0x7f95e9041e66
created by github.com/tendermint/tendermint/blockchain/v0.(*bpRequester).OnStart
	/home/warner/go/pkg/mod/github.com/agoric-labs/cometbft@v0.34.27-alpha.agoric.3/blockchain/v0/pool.go:536 +0x56
```

cc @JimLarson @michaelfig

**Comment by warner** [comment]
Here's the full stdout/stderr from the crashed node:

[9138-crash.txt](https://github.com/Agoric/agoric-sdk/files/14748070/9138-crash.txt)
