### ISSUE TITLE
flake in device-plugin › device › plugin after restart

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9188]
## What is the Problem Being Solved?

[This job](https://github.com/Agoric/agoric-sdk/actions/runs/8528679704/job/23363025472?pr=9006) failed spuriously:
```
not ok 57 - device-plugin › device › plugin after restart %ava-dur=8466ms
#   REJECTED from ava test.serial("plugin after restart"): (Error#1)
#   Error#1: anachrophobia in v1: missing syscalls
#     at Object.finishSimulation (.../swingset-vat/src/kernel/vat-warehouse.js:167:13)
#     at replayTranscript (.../swingset-vat/src/kernel/vat-warehouse.js:319:5)
#     at async ensureVatOnline (.../swingset-vat/src/kernel/vat-warehouse.js:374:1)
#     at async Object.start (.../swingset-vat/src/kernel/vat-warehouse.js:421:1)
#     at async Object.start (.../swingset-vat/src/kernel/kernel.js:1617:1)
#     at async makeSwingsetController (packages/SwingSet/src/controller/controller.js:258:3)
#     at async setupVatController (packages/SwingSet/test/device-plugin/test-device.js:62:13)
#     at async packages/SwingSet/test/device-plugin/test-device.js:100:5
```

**Comment by turadg** [comment]
[Hit this again today](https://github.com/Agoric/agoric-sdk/actions/runs/13061013091/job/36443893316?pr=10916),
```
        Error ***
          message: 'anachrophobia in v1 delivery d8: missing 12 syscall(s) at index sc0',
        ***
```

**Comment by turadg** [comment]
Closing b/c haven't seen in a while. Reopen if observed again.

**Comment by turadg** [comment]
A [job had failed](https://github.com/Agoric/agoric-sdk/actions/runs/14249513832/job/39938879814?pr=11100) just before my last comment,
```
not ok 59 - device-plugin › device › plugin after restart %ava-dur=6884ms
sc0: MISSING: ***"0":"vatstoreGet","1":"vom.rc.o-50","length":2***
sc1: MISSING: ***"0":"vatstoreGet","1":"vom.rc.o-51","length":2***
sc2: MISSING: ***"0":"vatstoreGet","1":"vom.rc.o-52","length":2***
sc3: MISSING: ***"0":"vatstoreGet","1":"vom.rc.o-53","length":2***
sc4: MISSING: ***"0":"vatstoreGet","1":"vom.rc.o-54","length":2***
sc5: MISSING: ***"0":"vatstoreGetNextKey","1":"vom.ir.o-50|","length":2***
sc6: MISSING: ***"0":"vatstoreGetNextKey","1":"vom.ir.o-51|","length":2***
sc7: MISSING: ***"0":"vatstoreGetNextKey","1":"vom.ir.o-52|","length":2***
sc8: MISSING: ***"0":"vatstoreGetNextKey","1":"vom.ir.o-53|","length":2***
sc9: MISSING: ***"0":"vatstoreGetNextKey","1":"vom.ir.o-54|","length":2***
sc10: MISSING: ***"0":"dropImports","1":***"0":"o-50","1":"o-51","2":"o-52","3":"o-53","4":"o-54","length":5***,"length":2***
sc11: MISSING: ***"0":"retireImports","1":***"0":"o-50","1":"o-51","2":"o-52","3":"o-53","4":"o-54","length":5***,"length":2***
Nested error under Error#1
Error#1: unfinished slog event kernel-init-start ***
    at slogDuration (file:///home/runner/work/agoric-sdk/agoric-sdk/packages/SwingSet/src/controller/controller.js:252:31)
    at async makeSwingsetController (file:///home/runner/work/agoric-sdk/agoric-sdk/packages/SwingSet/src/controller/controller.js:288:22)
    at async setupVatController (file:///home/runner/work/agoric-sdk/agoric-sdk/packages/SwingSet/test/device-plugin/device.test.js:62:13)
    at async file:///home/runner/work/agoric-sdk/agoric-sdk/packages/SwingSet/test/device-plugin/device.test.js:100:5
```

**Comment by turadg** [comment]
Fresh one https://github.com/Agoric/agoric-sdk/actions/runs/22194380753/job/64191373704?pr=12490

**Comment by turadg** [comment]
Last PR didn't solve it. I just it [again](https://github.com/Agoric/agoric-sdk/actions/runs/22330220091/job/64611034124?pr=12506). 
```
not ok 59 - device-plugin › device › plugin after restart
#   REJECTED from ava test("plugin after restart"): (Error#1)
#   Error#1: anachrophobia in v1 delivery d8: missing 12 syscall(s) at index sc0
#     at Object.finishSimulation (swingset-vat/src/kernel/vat-warehouse.js:188:21)
#     at replayTranscript (swingset-vat/src/kernel/vat-warehouse.js:344:11)
#     at async ensureVatOnline (swingset-vat/src/kernel/vat-warehouse.js:399:7)
#     at async Object.start (swingset-vat/src/kernel/vat-warehouse.js:445:7)
#     at async Object.start (swingset-vat/src/kernel/kernel.js:1847:5)
#     at async packages/SwingSet/src/controller/controller.js:376:5
#     at async slogDuration (packages/SwingSet/src/controller/controller.js:263:22)
#     at async makeSwingsetController (packages/SwingSet/src/controller/controller.js:305:22)
#     at async setupVatController (packages/SwingSet/test/device-plugin/device.test.js:62:13)
#     at async packages/SwingSet/test/device-plugin/device.test.js:104:5

  ---
    name: AssertionError
    details:
      'Rejected promise returned by test. Reason:': |-
        Error ***
          message: 'anachrophobia in v1 delivery d8: missing 12 syscall(s) at index sc0',
        ***
    message: Rejected promise returned by test
    at: 'Object.finishSimulation (swingset-vat/src/kernel/vat-warehouse.js:188:21)'
  ...
```

**Comment by mhofman** [comment]
We're still hitting this one A LOT
- https://github.com/Agoric/agoric-sdk/actions/runs/35117889763/job/104869483510#step:6:29
- https://github.com/Agoric/agoric-sdk/actions/runs/34996753189/job/104476266623#step:6:29
- https://github.com/Agoric/agoric-sdk/actions/runs/34309940448/job/102335186600#step:6:29
