### ISSUE TITLE
agd crashes when calling `agd query ibc connection params`

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#9222]
## Describe the bug
When calling `$ agd query ibc connection params` I get the following crash:
```shell
./bin/agd query ibc connection params
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101e5d368]

goroutine 1 [running]:
github.com/cosmos/ibc-go/v6/modules/core/03-connection/client/cli.GetCmdConnectionParams.func1(0x140013a7b08, {0x104597280?, 0x0?, 0x0?})
	/Users/ivanleichtling/go/pkg/mod/github.com/agoric-labs/ibc-go/v6@v6.2.1-alpha.agoric.3/modules/core/03-connection/client/cli/query.go:136 +0xd8
github.com/spf13/cobra.(*Command).execute(0x140013a7b08, {0x104597280, 0x0, 0x0})
	/Users/ivanleichtling/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x14001356008)
	/Users/ivanleichtling/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ivanleichtling/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/ivanleichtling/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x14001356008, {0x0, 0x0}, {0x140004f9e40, 0x1d})
	/Users/ivanleichtling/go/pkg/mod/github.com/agoric-labs/cosmos-sdk@v0.46.16-alpha.agoric.2.1/server/cmd/execute.go:36 +0x158
github.com/Agoric/agoric-sdk/golang/cosmos/daemon.RunWithController(0x140004fd5c0)
	/Users/ivanleichtling/source/agoric/agoric-sdk/golang/cosmos/daemon/main.go:47 +0x114
main.main()
	/Users/ivanleichtling/source/agoric/agoric-sdk/golang/cosmos/cmd/agd/main.go:157 +0x184
```

## To Reproduce
```shell
$ ./bin/agd query ibc connection params
```

## Expected behavior
No crash. Maybe an error message saying `--node` is missing?

## Platform Environment
MacOS: 14.4.1 
Node: v18.18.2
```shell
git describe --tags --always
@agoric/cosmic-swingset@0.41.3-1672-g860d051e8
```

## Additional context
`./bin/agd query ibc connection params --node https://main.rpc.agoric.net:443 -o json` will not fail.

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by JimLarson** [comment]
I get this error for upstream `cosmos/ibc-go` too:

```
$ agd query ibc connection params
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101566c4d]

goroutine 1 [running]:
github.com/cosmos/ibc-go/v6/modules/core/03-connection/client/cli.GetCmdConnectionParams.func1(0xc0012e9b00, {0x103b6f180?, 0x0?, 0x0?})
	/Users/jim/go/pkg/mod/github.com/cosmos/ibc-go/v6@v6.3.0/modules/core/03-connection/client/cli/query.go:136 +0x10d
...
```

**Comment by ivanlei** [comment]
This was fixed in a recent upgrade. No longer repros on `agoric-sdk/master`
