### ISSUE TITLE
Unable to cancel bid in CLI due to 'failed to send action. code:13'

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9363]
## Describe the bug
Attempts to cancel my active bid in the CLI fail due to 'failed to send action. code: 13'

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid cancel bid-1715636412878 --from test-acct-14 --keyring-backend=test 
(Error#1)
Error#1: failed to send action. code: 13

  at sendAction (packages/agoric-cli/src/lib/wallet.js:168:17)
  at Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:511:30)
  at async packages/agoric-cli/src/bin-agops.js:78:3

## To Reproduce
1. Have active bid
2. Attempt to cancel via inter bid cancel bid-1715636412878 --from test-acct-14 --keyring-backend=test

## Expected behavior
Bid should be cancelled

## Platform Environment

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

`@agoric/inter-protocol@0.16.2-u15.0`

**Comment by dckc** [comment]
What network did you submit the transaction to?

What version of code does `inter bid cancel` come from?

**Comment by dckc** [comment]
likely diagnosis: [error 13 is "insufficient fee"](https://github.com/agoric-labs/cosmos-sdk/blob/c03a8b7c63d7c0d031dc5828df231cd125ecb027/errors/errors_test.go)

recommended treatment: use `agd ... --fees=5000ubld` , in combination with `inter bid ... --generate-only`, as in [inter docs for placing bids](https://docs.inter.trade/user-how-to/bidding-for-liquidated-collateral#placing-bids)

docs for canceling should probably be updated
