### ISSUE TITLE
Otel slog sender does not handle `cosmic-swingset-upgrade-finish`

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#9569]
## Describe the bug
The otel slog sender does not correctly handle the `cosmic-swingset-upgrade-finish` event which results in noisy stderr during upgrades

## To Reproduce
Perform chain software upgrade on node with otel slog sender enabled

## Expected behavior
No errors

## Screenshots
```
Error tracing slog: {
  type: 'cosmic-swingset-upgrade-finish',
  blockHeight: 15523600,
  blockTime: 1719119730,
  time: 1719120112.841602,
  monotime: 184.16249005001782
} (Error#1)
Error#1: Check failed

  at Object.pop (packages/telemetry/src/slog-to-otel.js:448:11)
  at slogSender (packages/telemetry/src/slog-to-otel.js:918:15)
  at wrappedSlogSender (packages/telemetry/src/slog-to-otel.js:1072:7)
  at slogSender (packages/telemetry/src/make-slog-sender.js:154:11)
  at process.<anonymous> (packages/telemetry/src/slog-sender-pipe-entrypoint.js:116:15)
  at process.emit (node:events:517:28)
```

**Comment by mhofman** [comment]
Regexp that were previously used to cleanup output

```
s/Error tracing slog: \{\n(?:  .+\n)+\} \(([^)]+)\)\n((?:(?!\1:).*\n)*)\1:.*\n((?:[^ \n].*\n)*)(?:(?: .*|)\n)+/$2$3/gm
```
and 
```
s/Failed to flush slog sender \(([^)]+)\)\n((?:(?!\1:).*\n)*)\1:.*\n((?:[^ \n].*\n)*)\n/$2$3/gm
```

**Comment by mhofman** [comment]
This is actually a duplicate of https://github.com/Agoric/agoric-sdk/issues/8272
