### ISSUE TITLE
deployment-test is failing when using newer ssh-node images

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#9609]
## Describe the bug
After tagging `agoric-upgrade-16-rc0` / `sdk@44`, new docker images got built and published.

The deployment-test image currently uses the `ssh-node` image to run the 2 validator nodes of that test. For some reason it started failing with the following error when starting the agd service inside the validator containers:

```
Error#1: The module '/usr/src/agoric-sdk/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 109. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

  at makeSwingStore (packages/swing-store/src/swingStore.js:192:12)
  at openSwingStore (packages/swing-store/src/swingStore.js:647:10)
  at launch (packages/cosmic-swingset/src/launch-chain.js:351:42)
  at launchAndInitializeSwingSet (packages/cosmic-swingset/src/chain-main.js:466:21)
  at async toSwingSet (packages/cosmic-swingset/src/chain-main.js:676:24)
```

This makes very little sense because 109 is the module version for Electron, not Node.js, according to https://github.com/nodejs/node/blob/main/doc/abi_version_registry.json

According to the ansible config, the version of node inside the container is installed from node source. I verified locally and the installed version is 18.20.3 and has the expected 108 module version.

```
node -e "console.log(process.versions.modules)"
108
```

## To Reproduce
Run the docker deployment test using [ssh-node:44](https://github.com/agoric/agoric-sdk/pkgs/container/ssh-node/235324586?tag=44)

## Expected behavior
No errors

## Platform Environment
CI deployment-test

## Additional context
Restoring the previous image, [ssh-node:43](https://github.com/agoric/agoric-sdk/pkgs/container/ssh-node/206234670?tag=43), "solves" the issue:

```
skopeo copy --all docker://ghcr.io/agoric/ssh-node:43  docker://ghcr.io/agoric/ssh-node:latest
```

**Comment by mhofman** [comment]
Above command seems to have auth issues sometimes, know to work with
```
skopeo copy --all docker://ghcr.io/agoric/ssh-node@sha256:107ce5c17744e54fe2ea76ee4c52ace0e5bef4dd2aa6a67172219dfec001ae68  docker://ghcr.io/agoric/ssh-node:latest
```
using docker image `quay.io/skopeo/stable@sha256:30ad61b97acf899e4eb7d592b8a0a3431282d2c291a02de38437bf7178048605`

**Comment by rabi-siddique** [comment]
@mhofman, thank you for the detailed bug report. I'm not immediately familiar with the process for running the docker deployment test using` ssh-node:44`. Could you provide a bit more detail on that or point me towards the relevant documentation? I want to understand this better and ensure everything is set up correctly.

**Comment by mhofman** [comment]
The deployment test is run by CI normally, but I've been using https://github.com/Agoric/agoric-sdk/blob/master/scripts/run-deployment-integration.sh to replicate locally. I think if you pull `ghcr.io/agoric/ssh-node@44` (or the newer `47` from the final u16 release), and tag it as `latest`, you should be able to reproduce.

**Comment by mhofman** [comment]
Btw, that image is built from https://github.com/Agoric/agoric-sdk/blob/master/packages/deployment/Dockerfile.ssh-node

**Comment by mhofman** [comment]
This issue is biting us again in https://github.com/Agoric/agoric-sdk/pull/10979.

The root problem is that Terraform in the deployment-test uses `ghcr.io/agoric/ssh-node:latest` pulled from the registry instead of one built locally from the current SDK. It might be as simple as building and tagging that image as `unreleased` and switching the terraform definition to use that tag, hoping that it would use the local image instead (e.g. how multichain and docket-test-build both use a locally built image of `agoric-sdk`)

It would be better if we could use `agoric-sdk` instead of `ssh-node` for this test, or deprecate the test altogether.

**Comment by usmanmani1122** [comment]
What is the use case for the `ssh-node` image? I see it only used in deployment scripts for `ansible` (apart from the CI job). Do we still use it?
cc: @michaelfig @mhofman

**Comment by mhofman** [comment]
@michaelfig can provide more details, but I believe the idea was to test using steps that validators may be more likely to use (checkout and build our sdk), rather than using our docker image.

Given that we want to [revamp our integration testing](https://github.com/Agoric/agoric-private/issues/302#issuecomment-2779750579) story, it might not be worth fixing this particular issue.

**Comment by mhofman** [comment]
Also we have not been hitting this particular issue as originally reported in recent releases.
