### ISSUE TITLE
sequence mismatch flake in multichain-testing

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9934]
## What is the Problem Being Solved?

```
  Error: rewards available on osmosis condition failed after 8 retries.
    at retryUntilCondition (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/sleep.ts:28:11)
    at async file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/stake-ica.test.ts:99:23
```

instances
- https://github.com/Agoric/agoric-sdk/actions/runs/10482566227/job/29033890661?pr=9395
- https://github.com/Agoric/agoric-sdk/actions/runs/10533760653/job/29190278931?pr=9953

**Comment by turadg** [comment]
Similar if not same:
- https://github.com/Agoric/agoric-sdk/actions/runs/10797610413/job/29949245444?pr=10053

```
Error {
    message: 'osmosis-makeAccountAndGetBalancesQuery-1725990048002 offer result is in vstorage condition failed after 25 retries.',
  }

  Error: osmosis-makeAccountAndGetBalancesQuery-1725990048002 offer result is in vstorage condition failed after 25 retries.
```

**Comment by turadg** [comment]
Today:
- https://github.com/Agoric/agoric-sdk/actions/runs/10950221384/job/30405079980?pr=10121

```
  ✘ Timed out while running tests

  4 tests were pending in test/send-anywhere.test.ts

  ◌ send-anywhere › send-anywhere osmosis1
    ℹ Create a receiving wallet for the send-anywhere transfer
    ℹ Create an agoric smart wallet to initiate send-anywhere transfer
  ◌ send-anywhere › send-anywhere osmosis2
  ◌ send-anywhere › send-anywhere cosmoshub1
  ◌ send-anywhere › send-anywhere cosmoshub2
```

**Comment by 0xpatrickdev** [comment]
From Oct 5:

- https://github.com/Agoric/agoric-sdk/actions/runs/11196614306/attempts/1

```
  ✘ Timed out while running tests

  1 tests were pending in test/stake-ica.test.ts

  ◌ stake-ica › send wallet offers to stakeOsmo contract
```

**Comment by turadg** [comment]
Lately I've been seeing [this one](https://github.com/Agoric/agoric-sdk/actions/runs/12912537975/job/36007612639?pr=10872) a lot in the **Override Chain Registry step**:
```
installing bundles
$$$ agd tx swingset install-bundle @/tmp/contracts/b1-874c2b8f3ffe7a2c2d9d0b2cb5d188d835b9522eb2f53eb77866d761521dc6a06b1002bd9492aed5dca50c8f12aea5a5ca62942f11ec0856a80b55c25261e385.json --gas auto --keyring-backend test --chain-id agoriclocal --from agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
(Error#1)
Error#1: Command failed: kubectl exec -i agoriclocal-genesis-0 -c validator --tty=false -- agd tx swingset install-bundle @/tmp/contracts/b1-874c2b8f3ffe7a2c2d9d0b2cb5d188d835b9522eb2f53eb77866d761521dc6a06b1002bd9492aed5dca50c8f12aea5a5ca629[42](https://github.com/Agoric/agoric-sdk/actions/runs/12912537975/job/36007612639?pr=10872#step:11:43)f11ec0856a80b55c25261e385.json --gas auto --keyring-backend test --chain-id agoriclocal --from agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
```

**Comment by turadg** [comment]
[Same step](https://github.com/Agoric/agoric-sdk/actions/runs/12931462774/job/36065394455?pr=10872) but different error:

```
installing bundles
$$$ agd tx swingset install-bundle @/tmp/contracts/b1-874c2b8f3ffe7a2c2d9d0b2cb5d188d835b9522eb2f53eb77866d761521dc6a06b1002bd9492aed5dca50c8f12aea5a5ca62942f11ec0856a80b55c25261e385.json --gas auto --keyring-backend test --chain-id agoriclocal --from agoric1hm54wrxsv8e3pnw6lxj5lssfpexn48xtj6fhxw --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
(Error#1)
Error#1: account sequence mismatch, expected 31, got 30: incorrect account sequence
    at Object.tx (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/agd-lib.js:146:19)
    at installBundle (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/e2e-tools.js:109:24)
    at async Object.installBundles (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/e2e-tools.js:498:31)
    at async deployBuilder (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/deploy.ts:39:5)
    at async main (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/scripts/deploy-cli.ts:33:5)

output: <Buffer 7b 22 68 65 69 67 68 74 22 3a 22 30 22 2c 22 74 78 68 61 73 68 22 3a 22 30 30 31 30 43 43 33 43 44 39 38 35 36 30 30 39 45 32 36 33 35 32 [41](https://github.com/Agoric/agoric-sdk/actions/runs/12931462774/job/36065394455?pr=10872#step:11:42) 31 45 46 ... 268 more bytes>
(Error#2)
Error#2: Check failed
    at makeError (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/node_modules/ses/src/error/assert.js:350:61)
```

**Comment by mhofman** [comment]
> [Same step](https://github.com/Agoric/agoric-sdk/actions/runs/12931462774/job/36065394455?pr=10872) but different error:

An account sequence mismatch error is either different or an interesting diagnostic. It means that some step likely before sent a tx but didn't wait for it to be included in a block, so the publish tx used the same seq number than the one that was still pending in the memoool

**Comment by turadg** [comment]
A [new one](https://github.com/Agoric/agoric-sdk/actions/runs/12939709219/job/36092543387?pr=10872),
```
    ℹ recipientAddress agoric10rchp2cj5c200d4n8s3qymdcmg444nq328lugz5apl9q6wt2ka5pc6me8az423pav9nk7unfvvckcapc89u82wtdvaun2et2xq68qmnkwq6hscfc89j8wvnrw4crvanvdsenvetwqqsq9gnfzy
    ℹ got forwardingAddress noble1fr0rd9l2m5cvwzwx5760zguarh5pd098csnc9q
    ℹ REJECTED from ava test.serial() "advance 1600000000 uusdc to agoric and settle": (Error#1)
    ℹ Error#1: Error: conflicting evidence for (a string)
    ℹ     at Object.submit (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/fast-usdc/fu-actors.ts:128:19)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/13019384922/job/36316349011
```
----- E2ET.10  2 { step: 'bank send', delay: 1 } ...
----- E2ET.10  3 { step: 'bank send', delay: 1 } ...
{ provisioning: 'agoric1ujmk0492mauq2f2vrcn7ylq3w3x55k0ap9mt2p' }
$$$ agd tx swingset provision-one my-wallet agoric1ujmk0492mauq2f2vrcn7ylq3w3x55k0ap9mt2p SMART_WALLET --keyring-backend test --chain-id agoriclocal --from agoric1ujmk0492mauq2f2vrcn7ylq3w3x55k0ap9mt2p --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
----- E2ET.10  4 { step: 'bank send', delay: 1 } ...
{ provisioning: 'agoric1dh04lnl7epr7l4cpvqqprxvam7ewdswj7yv6ep' }
$$$ agd tx swingset provision-one my-wallet agoric1dh04lnl7epr7l4cpvqqprxvam7ewdswj7yv6ep SMART_WALLET --keyring-backend test --chain-id agoriclocal --from agoric1dh04lnl7epr7l4cpvqqprxvam7ewdswj7yv6ep --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
  ✘ [fail]: fast-usdc › before hook Rejected promise returned by test
    ℹ setupTestKeys: {
        feeDest: 'agoric1fyuzwptu2fnjw3h90rnuhkd6p5zexs6u55pg7j',
        lp: 'agoric1khehvyyys49qjd23w7uhr8g587wf0ppjnaf4pv',
        oracle1: 'agoric1yupasge[45](https://github.com/Agoric/agoric-sdk/actions/runs/13019384922/job/36316349011#step:14:46)28pgkszg9v328x4faxtkldsnygwjl',
        oracle2: 'agoric1dh04lnl7epr7l4cpvqqprxvam7ewdswj7yv6ep',
        oracle3: 'agoric1ujmk0492mauq2f2vrcn7ylq3w3x55k0ap9mt2p',
      }
    ℹ REJECTED from ava test.before(): (Error#1)
    ℹ Error#1: wallet in vstorage agoric1yupasge4528pgkszg9v328x4faxtkldsnygwjl condition failed after 15 retries.
    ℹ     at retryUntilCondition (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/sleep.ts:59:9)
          at async provisionSmartWallet (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/tools/e2e-tools.js:206:16)
          at async Promise.all (index 0)
          at async makeTestContext (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/fast-usdc/fast-usdc.test.ts:59:21)
          at async file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/test/fast-usdc/fast-usdc.test.ts:120:37
```

**Comment by turadg** [comment]
[provisioning failure again](https://github.com/Agoric/agoric-sdk/actions/runs/13116668078/job/36592596236?pr=10922)

**Comment by turadg** [comment]
[Failing even with 30 retries](https://github.com/Agoric/agoric-sdk/actions/runs/13170380971/job/36759526613?pr=10941#step:14:408)

**Comment by dckc** [comment]
[me too](https://github.com/Agoric/agoric-sdk/actions/runs/13189869770/job/36820501198?pr=10939#step:14:514)

**Comment by gibson042** [comment]
[another](https://github.com/Agoric/agoric-sdk/actions/runs/13220266900/job/36904392780?pr=10954#step:14:523)

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/13326568486/job/37223463516?pr=11006#step:14:219
https://github.com/Agoric/agoric-sdk/actions/runs/13326568486/job/37223463179?pr=11006#step:14:397

**Comment by mhofman** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/13524515214/job/37791595573?pr=11036

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/13597601234/attempts/1?pr=11066

**Comment by turadg** [comment]
The Fast USDC one is more reliable. It's the Orchestration one that's failing in https://github.com/Agoric/agoric-sdk/actions/runs/13697343438

The reason is that it provisions so many wallets. The validator logs (in artifacts) show,
```
2025-03-06T11:31:11.962Z SwingSet: vat: v27: ----- ProvPool.4  18 PLEASE_PROVISION { address: 'agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc', autoProvision: false, blockHeight: 467, blockTime: 1741260671, nickname: 'my-wallet', powerFlags: [ 'SMART_WALLET' ], submitter: 'agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc', type: 'PLEASE_PROVISION' }
2025-03-06T11:31:11.998Z SwingSet: ls: v10: Logging sent error stack (Error#1)
2025-03-06T11:31:11.998Z SwingSet: ls: v10: Error#1: cannot grab 250000uist coins: 0uist is smaller than 250000uist: insufficient funds
2025-03-06T11:31:11.998Z SwingSet: ls: v10: Error: cannot grab 250000uist coins: 0uist is smaller than 250000uist: insufficient funds
 at apply ()
 at Error (/bundled-source/.../node_modules/ses/src/error/tame-error-constructor.js:60)
 at outbound (.../vats/src/bridge.js:162)
 at outbound (.../vats/src/bridge.js:157)
 at apply ()
 at In "outbound" method of (BridgeManagerKit privateOutbounder) (/bundled-source/.../node_modules/@endo/exo/src/exo-tools.js:171)
 at apply ()
 at localApplyMethod (/bundled-source/.../node_modules/@endo/eventual-send/src/local.js:126)
 at apply ()
 at dispatchToHandler (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:159)
 at win (/bundled-source/.../node_modules/@endo/eventual-send/src/handled-promise.js:514)
 at ()
```

But the test doesn't know about that,
```
2025-03-06T11:31:12.0782080Z ----- Agd.10  16 $ agd tx swingset provision-one my-wallet agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc SMART_WALLET --keyring-backend test --chain-id agoriclocal --from agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc --broadcast-mode block --gas auto --gas-adjustment 1.4 --yes --output json
2025-03-06T11:31:12.0784081Z ----- Agd.10  17 agd returned; {
2025-03-06T11:31:12.0784448Z   height: '467',
2025-03-06T11:31:12.0785035Z   txhash: 'EB8D0F0261AE04FE95C488187B4F7BDF29FD27882A9B28B6311D45055B313E43',
2025-03-06T11:31:12.0785615Z   codespace: '',
2025-03-06T11:31:12.0785888Z   code: 0,
2025-03-06T11:31:12.0786824Z   data: '12270A252F61676F7269632E7377696E677365742E4D736750726F766973696F6E526573706F6E7365',
2025-03-06T11:31:12.0791881Z   raw_log: '[{"msg_index":0,"events":[{"type":"coin_received","attributes":[{"key":"receiver","value":"agoric1ae0lmtzlgrcnla9xjkpaarq5d5dfez63h3nucl"},{"key":"amount","value":"10000000ubld"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc"},{"key":"amount","value":"10000000ubld"}]},{"type":"message","attributes":[{"key":"action","value":"/agoric.swingset.MsgProvision"},{"key":"sender","value":"agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"agoric1ae0lmtzlgrcnla9xjkpaarq5d5dfez63h3nucl"},{"key":"sender","value":"agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc"},{"key":"amount","value":"10000000ubld"}]}]}]',
2025-03-06T11:31:12.0795654Z   logs: [ { msg_index: 0, log: '', events: [Array] } ],
2025-03-06T11:31:12.0796075Z   info: '',
2025-03-06T11:31:12.0796333Z   gas_wanted: '169363',
2025-03-06T11:31:12.0796865Z   gas_used: '119236',
2025-03-06T11:31:12.0797179Z   tx: null,
2025-03-06T11:31:12.0797442Z   timestamp: '',
2025-03-06T11:31:12.0797724Z   events: [
2025-03-06T11:31:12.0798041Z     { type: 'tx', attributes: [Array] },
2025-03-06T11:31:12.0798481Z     { type: 'tx', attributes: [Array] },
2025-03-06T11:31:12.0798910Z     { type: 'tx', attributes: [Array] },
2025-03-06T11:31:12.0799354Z     { type: 'message', attributes: [Array] },
2025-03-06T11:31:12.0799828Z     { type: 'coin_spent', attributes: [Array] },
2025-03-06T11:31:12.0800326Z     { type: 'coin_received', attributes: [Array] },
2025-03-06T11:31:12.0800812Z     { type: 'transfer', attributes: [Array] },
2025-03-06T11:31:12.0801286Z     { type: 'message', attributes: [Array] }
2025-03-06T11:31:12.0801664Z   ]
2025-03-06T11:31:12.0801915Z }
2025-03-06T11:31:12.0802652Z ----- E2ET.11  70 waiting for wallet to appear in vstorage agoric17cexjp9zxc8wyqf7da92gmcw9yk4twt02rfzgc
```

Can we get `please-provision` to fail in the test when it doesn't work?

**Comment by mhofman** [comment]
> Can we get `please-provision` to fail in the test when it doesn't work?

Can you clarify?  `agd` client doesn't know the outcome of the execution of SwingSet for any tx, whether smart wallet spend, or provisioning. I believe that's what agops attempts to solve (or is it another tool?), by watching vstorage for the outcome of the execution. In this case I suppose it'd be the existence of the `published.wallet.agoric1....` entry.

**Comment by turadg** [comment]
It wasn't clear but I was just thinking out loud. See [the Slack thread](https://agoricopco.slack.com/archives/C038E5369FT/p1741302528696149?thread_ts=1741287379.084499&cid=C038E5369FT) for the latest

**Comment by turadg** [comment]
When the wallets can't be provisioned, it's because `fund-provision-pool` failed:
```
2025-03-07T23:36:01.0362399Z kubectl exec -i agoriclocal-genesis-0 -c validator -- agd tx bank send faucet agoric1megzytg65cyrgzs6fvzxgrcqvwwl7ugpt62346 999750000uist -y -b block
2025-03-07T23:36:01.1717846Z {"height":"0","txhash":"4816BDC7F647A11F5607D3143D378DC7E1A63F84C56237EE7E6117C9AC10ED52","codespace":"sdk","code":32,"data":"","raw_log":"account sequence mismatch, expected 30, got 29: incorrect account sequence","logs":[],"info":"","gas_wanted":"200000","gas_used":"31838","tx":null,"timestamp":"","events":[]}
2025-03-07T23:36:01.1771752Z kubectl exec -i agoriclocal-genesis-0 -c validator -- agd query bank balances agoric1megzytg65cyrgzs6fvzxgrcqvwwl7ugpt62346
2025-03-07T23:36:01.3194230Z {"balances":[],"pagination":{"next_key":null,"total":"0"}}
```

**Comment by turadg** [comment]
Happening still with the [block mode](https://github.com/Agoric/agoric-sdk/blob/master/multichain-testing/scripts/fund-provision-pool.ts#L51-L52) and retry,
```
Funding provision pool at agoric1megzytg65cyrgzs6fvzxgrcqvwwl7ugpt62346 with 999750000uist...
Error funding provision pool: Error: Transaction failed: account sequence mismatch, expected 27, got 26: incorrect account sequence
    at fundProvisionPool (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/scripts/fund-provision-pool.ts:56:13)
    at async main (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/scripts/fund-provision-pool.ts:1[23](https://github.com/Agoric/agoric-sdk/actions/runs/13824176678/job/38675991674?pr=11110#step:11:24):17)
Trying again...
Funding provision pool at agoric1megzytg65cyrgzs6fvzxgrcqvwwl7ugpt62346 with 999750000uist...
Error funding provision pool: Error: Transaction failed: account sequence mismatch, expected 27, got 26: incorrect account sequence
    at fundProvisionPool (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/scripts/fund-provision-pool.ts:56:13)
    at async main (file:///home/runner/work/agoric-sdk/agoric-sdk/agoric-sdk/multichain-testing/scripts/fund-provision-pool.ts:1[27](https://github.com/Agoric/agoric-sdk/actions/runs/13824176678/job/38675991674?pr=11110#step:11:28):15)
make: *** [Makefile:76: fund-provision-pool] Error 1
```

**Comment by 0xpatrickdev** [comment]
I opened a PR that adds `waitForBlock(1)` logic to the Fund Provision Step: https://github.com/Agoric/agoric-sdk/pull/11129

This step is the first to occur after all pods are ready and ports are forwarded, so it's a bit surprising to see a concurrent signing request from the `faucet` account. Nonetheless, the `waitForBlock(1)` added before attempting the bank transfer should increase reliability here.

**Comment by mhofman** [comment]
Reopening since it looks like the problem has moved to the chain registry section now?

https://github.com/Agoric/agoric-sdk/actions/runs/13998860883/job/39200487363#step:12:45

**Comment by turadg** [comment]
If this pops up again, we can try [checking specifically for the sequence number and bumping it](https://github.com/Agoric/agoric-sdk/pull/11155#discussion_r2011014876).

**Comment by turadg** [comment]
[Strikes again](https://github.com/Agoric/agoric-sdk/actions/runs/14272182859/job/40007723487?pr=11208)

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-sdk/actions/runs/14577780012/job/40887630338?pr=11299

**Comment by turadg** [comment]
Next approach, kick it down the road: https://github.com/nick-fields/retry/

Add a step after each retry that checks whether it had flaked and if so fires a webhook. 

It can examine [the outputs ](https://github.com/nick-fields/retry/?tab=readme-ov-file#outputs) for `exit_code == 0` and `total_attempts >1 `

@mhofman would like to review the PR doing this
