### ISSUE TITLE
XSnap REPL

### ISSUE THREAD

**Issue by kriskowal** [Agoric/Agoric#9955]
## Describe the bug
The `xsrepl` tool for debugging xsnap has been broken for some time.

## To Reproduce
1. Go to 'packages/xsnap'
2. Run `yarn xsrepl`

## Expected behavior
This should open up a CLI REPL you can use to send commands to an xsnap process. It’s useful for debugging xsnap.

## Platform Environment
 - agoric-sdk `5cd99eae25a3194dd04e77bc5bae23cd9ead981d`

## Additional context
The tool doesn’t have validation in CI so is doomed to rot. We should either delete it or CI it.

**Comment by mhofman** [comment]
I used this fairly recently, maybe a few weeks ago, what's broken about it?

**Comment by mhofman** [comment]
I just verified that it's working for me on master as of `7a08c6af641c62d8b0ef4a0c35090b6216a5be34`

**Comment by kriskowal** [comment]
I’ve lost track of the circumstances this was originally reported on, but content that it’s working on master until we get a more specific isolation.

**Comment by erights** [comment]
> Steps to reproduce the behavior:
> 1. Go to 'packages/xsnap'
> 2. Run `yarn xsrepl`

Doing that runs the xsrepl at `agoric-sdk/node_modules/.bin/xsrepl`. In that repl, a thrown error seems to cause that repl to hang forever, or until I type a control-C.

```
$ yarn xsrepl
yarn run v1.22.22
$ /Users/markmiller/src/ongithub/agoric/agoric-sdk/node_modules/.bin/xsrepl
xs> 2n/0n;
(Error#1)
Error#1: Uncaught exception in <unnamed xsnap worker>: RangeError: (anonymous-543): zero divider
  at runToIdle (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/xsnap/src/xsnap.js:334:15)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Indeed, in xsnap package.json scripts at

https://github.com/Agoric/agoric-sdk/blob/3c66f4b3bb8e2a92455685797319ef0657a42038/packages/xsnap/package.json#L13-L14

there is an entry for `"repl":` but no entry for `"xsrepl":`. So if I do a `yarn repl`, it does run `src/xsrepl.js`, but this also hangs forever on a thrown error:

```
$ yarn repl
yarn run v1.22.22
$ node src/xsrepl.js
xs> 2n/0n
(Error#1)
Error#1: Uncaught exception in <unnamed xsnap worker>: RangeError: (anonymous-543): zero divider
  at runToIdle (file:///Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/xsnap/src/xsnap.js:334:15)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Reopening.

**Comment by erights** [comment]
Attn @kriskowal @mhofman @phoddie

**Comment by phoddie** [comment]
Is there something Team Moddable should look at here?

**Comment by mhofman** [comment]
I don't think there is anything Moddable needs to do here. We just need to better handle errors thrown in evaluated commands from our repl.

Arguably this should be filed as a separate issue.

**Comment by mhofman** [comment]
Potential fix:

```diff
diff --git a/packages/xsnap/src/xsrepl.js b/packages/xsnap/src/xsrepl.js
index 3eede346bb..bfeece538b 100755
--- a/packages/xsnap/src/xsrepl.js
+++ b/packages/xsnap/src/xsrepl.js
@@ -31,7 +31,12 @@ async function main() {
    * @returns {Promise<Uint8Array>}
    */
   async function handleCommand(message) {
-    console.log(decoder.decode(message));
+    const { success, result, error } = JSON.parse(decoder.decode(message));
+    if (success) {
+      console.log(result);
+    } else {
+      console.error(error);
+    }
     return new Uint8Array();
   }
 
@@ -50,11 +55,22 @@ async function main() {
     });
     function handleCommand(request) {
       const command = new TextDecoder().decode(request);
-      let result = compartment.evaluate(command);
-      if (result === undefined) {
-        result = null;
+      let result;
+      let error;
+      let success;
+      try {
+        result = compartment.evaluate(command);
+        success = true;
+      } catch (e) {
+        success = false;
+        try {
+          const {name, message, stack} = e;
+          error = {name, message, stack};
+        } catch (_e) {
+          error = String(e);
+        }
       }
-      issueCommand(new TextEncoder().encode(JSON.stringify(result, null, 4)).buffer);
+      issueCommand(new TextEncoder().encode(JSON.stringify({success, result, error}, null, 4)).buffer);
     }
   `);
```

**Comment by erights** [comment]
Time for a PR?
